### ISSUE TITLE
Website should show 1.17.4 as the latest release (currently shows 1.17.3)

### ISSUE THREAD

**Issue by pshendry** [sinonjs/sinon#1096]
Not sure if there's a reason for that, but I've been trying to diagnose some behaviour that's confusing me and I noticed the discrepancy.

**Comment by pshendry** [comment]
On closer inspection it looks like other parts of the website also haven't been updated since the 1.17.4 release; the downloads page lists 1.17.3 as the latest.

**Comment by fatso83** [comment]
You are correct, but someone else than me needs to update the current docs, as I have been unable to build it due to some weird Leiningen/Java/Clojure error.

We are currently busy trying to get 2.0 out the door, but once that's out we soon have a new site up that should be way easier to keep up to date (#991).

**Comment by pshendry** [comment]
Okay, it's not impacting me or anything so feel free to close if fixing is not worth it.

**Comment by fearphage** [comment]
`v1.17.4` is deprecated due to regressions (#1040).
