### ISSUE TITLE
sinon stub- cannot stub arrow function in a class

### ISSUE THREAD

**Issue by repspark-trh** [sinonjs/sinon#1136]
* Sinon version : v2.0.0-pre.2
* Environment   : Windows 10
* Other libraries you are using: Typescript, babel, mocha, chai

**What did you expect to happen?**
I expected to be able to stub an arrow function in a class. 

**What actually happens**
I can't stub an arrow function, however, I can stub the class prototype function. 

```
FAILED TESTS:
  ExampleClass tests
    × should stub thisDoesntWork arrow function
      Chrome 52.0.2743 (Windows 10 0.0.0)
    TypeError: Attempted to wrap undefined property thisDoesntWork as function
        at wrapMethod (webpack:///~/sinon/pkg/sinon.js:3138:0 <- test-bundler.js:7377:21)
        at Object.stub (webpack:///~/sinon/pkg/sinon.js:2472:0 <- test-bundler.js:6711:12)
        at Context.<anonymous> (webpack:///src/stores/sinon.test.ts:22:51 <- test-bundler.js:96197:72)
```

**How to reproduce**
```
export class ExampleClass {
    thisWorks() {
        return 0;
    }

    thisDoesntWork = () => {
        return 0;
    }
}

describe("ExampleClass tests", () => {
    it("should stub thisWorks function", () => {
        let stubFunctionA = sinon.stub(ExampleClass.prototype, "thisWorks");
    });
    it("should stub thisDoesntWork arrow function", () => {
        let stubFunctionB = sinon.stub(ExampleClass, "thisDoesntWork");
    });
});
```

**Comment by fatso83** [comment]
This is food for the upcoming new documentation site where we hope to publish some more tutorial oriented articles on stubbing, spying, etc in the context of ES2015.

Generally when you come across issues like this it is very helpful in remembering one simple fact: ES2015 is often just syntactic sugar on top of simple ES5 constructs. Meaning, when you don't understand why something happens (or doesn't happen), try deconstructing the code into its ES5 equivalent. The simplest way (which is what I just did) is to just [paste the example code into the Babel playground](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=export%20class%20ExampleClass%20%7B%0A%20%20%20%20thisWorks()%20%7B%0A%20%20%20%20%20%20%20%20return%200%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20thisDoesntWork%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20return%200%3B%0A%20%20%20%20%7D%0A%7D) and see what the ES2015/ES6 code compiles into.

Doing that, one sees a few things:
<details>
<summary>The transpiled code from Babel</summary>
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var ExampleClass = exports.ExampleClass = function () {
    function ExampleClass() {
        _classCallCheck(this, ExampleClass);

        this.thisDoesntWork = function () {
            return 0;
        };
    }

    _createClass(ExampleClass, [{
        key: "thisWorks",
        value: function thisWorks() {
            return 0;
        }
    }]);

    return ExampleClass;
}();
```
</details>

The first thing I spot is that arrow functions are simply _instance methods_. That means a few things:
1. they do not exist until object creation. 
2. they cannot be stubbed by modifying the prototype, since they do not exist on the prototype
3. they cannot be stubbed by modifying the constructor object, since their definition is hidden within the closure.

Knowing all of this, it is simply to change your failing test to this:
```javascript
    it("should stub thisDoesntWork arrow function", () => {
        var example = new ExampleClass();
        let stubFunctionB = sinon.stub(example, "thisDoesntWork", () => "actually it does work" );
    });
```

Good luck.

**Comment by golergka** [comment]
Does it mean that for very arrow method my class has, I have to write additional line like this:

```Typescript
classStub.methodName = sinon.stub(classStub, "methodName");
```

Is there any way to stub all the arrow functions automatically when I create the stub for the class?
