### ISSUE TITLE
stubbing module exports with closures

### ISSUE THREAD

**Issue by markbrown4** [sinonjs/sinon#1248]
I can't seem to find a way to gracefully stub the exported `a()` here:

```js
// lib.js
const a = () => {}
const b = () => {
  a()
}

module.exports = { a, b }
```

```js
// test.js
const assert = require('assert')
const sinon = require('sinon')

const lib = require('./lib')
const stub = sinon.stub(lib, 'a')
lib.b()
assert(stub.called)
```

I'm guessing this fails because b has it's own copy of a.
I can do something like this which makes the test pass but it makes me want to take a shower.

```js
const a = () => {}
const b = () => {
  toExport.a()
}

const toExport = { a, b }

module.exports = toExport
```

Any other options?

Cheers,

**Comment by fatso83** [comment]
You need to have a way of injecting your stub to do this cleanly. Something like

```javascript
...
module.exports = { 
                                a, 
                                b, 
                                __injectA = function(fn){ a = fn; },
                                __injectB = function(fn){ b = fn; } 
}
```

Of course, since you are changing the internals of the module it will affect everything else using this module. If you want to do this without altering some kind of global state, you will need to create those functions in a closure created by some exported init function.

**Comment by markbrown4** [comment]
Ah, that makes sense. Thank you!
