### ISSUE TITLE
Issue with old releases no longer being published on new site

### ISSUE THREAD

**Issue by jcope2013** [sinonjs/sinon#1308]
now that the new site is live (https://github.com/sinonjs/sinon/issues/1220), a lot of the old releases are not published anymore, this is an issue as a lot of repo's depend on older releases

https://github.com/search?q=http%3A%2F%2Fsinonjs.org%2Freleases%2F&type=Code&utf8=%E2%9C%93 (47,412 results found) a lot of these no longer work, can you publish all of the older releases again so that downstream repo's continue working properly? 

one specific example, there are many more but this repo I use relies on http://sinonjs.org/releases/sinon-1.12.2.js in it's bower.json which is no longer there which causes other issues

https://github.com/danielspaniel/ember-data-factory-guy/blob/v1.13.10/bower.json

**Comment by mantoni** [comment]
We never supported bower and the website URLs are not part of our API. The issue lies within people using the URLs instead of official releases. If anybody needs a different mechanism, they can maintain it. If you rely on these, you should fix it ASAP because there is no guarantee that the files will live in that place under that name in the future.

@sinonjs/owners Who has a handle to the old release files and can deploy them again?

**Comment by mantoni** [comment]
Same as #1306.

**Comment by mantoni** [comment]
The files are restored.
