### ISSUE TITLE
Deep Equal should not exact equal for error

### ISSUE THREAD

**Issue by stephanwlee** [sinonjs/sinon#1322]
Hi Sinon! Thank you for providing awesome library with cool new features added to the pre-release version. I have been using pre for newly introduced API (I was going to write extension myself and I found the code whiling digging through the source) but .6 release broke our large test suite.

* Sinon version : 2.0.0-pre.6
* Environment   : macOS with Node6+
* Example URL   :
* Other libraries you are using:
Mocha, Babel

**What did you expect to happen?**
I did not expect `.deep.equals` assertion to fail when different but "equal" instance of error was passed
**What actually happens**
For any subclass of `Error`, deep `equals` does exact `equals`. https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/core/deep-equal.js#L54-L56

**Comment by lucasfcosta** [comment]
Hi everyone!

This is indeed something simple to solve and I'm willing to do a PR for it. However, I'd like to suggest a different approach other than just fixing that `if` clause.
In `Chai` we've got a module called [`deep-eql`](https://github.com/chaijs/deep-eql) which does deep equality checks. [It has been extensively tested and fine tuned for performance](https://github.com/chaijs/deep-eql/pull/14#issuecomment-252451358) and works fine on Chai's core.

By adopting the same library we would also be working on the same codebase in the future in order to improve it and make it better for every project using it.

Also, it still allows us to have [the `use` method](https://github.com/sinonjs/sinon/blob/e4013371207d55f91d9fc99d0ff85532e3ed57e0/lib/sinon/util/core/deep-equal.js#L99) due to [the `comparator` argument this library accepts](https://github.com/chaijs/deep-eql/blob/ff1b5dab1c10a9cd269090a220987c0dc1abe87d/index.js#L112).

If you don't want to adopt it it's fine too, but I just thought about suggesting it before solving it.

**Comment by mroderick** [comment]
@lucasfcosta I like the proposed solution. It might be a bit of challenge to wrangle `match` to become a comparator option ... but it looks like you like the challenges ;)

I would love to see a PR that reduces the size of the codebase
