### ISSUE TITLE
Sinon fakeserver turn string to regexp

### ISSUE THREAD

**Issue by rozaev** [sinonjs/sinon#1403]
* Sinon version : 2.2.0
* Environment   : Any browser
* Example URL   : http://jsbin.com/wepubudabu/edit?html,console
* Other libraries you are using: None

**What did you expect to happen?**
I expect that when I provide url as string it will be a string, not a Regex.

**What actually happens**
Sinon turn URL string to regexp

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

Reproduce: http://jsbin.com/wepubudabu/edit?html,console

Note:
It's work in 1.* branch. I update sinon up to 2.2.0 and my tests failed.

Intern docs says that it's valid:
http://sinonjs.org/releases/v2.2.0/fake-xhr-and-server/

> server.respondWith(method, url, response);

This bug already happen: https://github.com/sinonjs/sinon/issues/201

**Comment by mroderick** [comment]
Is https://github.com/sinonjs/sinon/issues/336 related to this? Is this the same problem?

**Comment by rozaev** [comment]
@mroderick Yes it's the same.

**Comment by mroderick** [comment]
@rozaev I've dug into this issue

The change that causes the observable difference was introduced in b5d10a40daf02f5263ce078170ab8f8b934975f3, which improves the fake server.

The `responses` property that is accessed in your example is considered private, and is likely to change as Sinon changes.

The issue described above is not related to #201, #336

The documentation doesn't mention the `.responses` property anywhere that I can find, which is preferable, since it's not meant to be used outside the library.

If you feel it is essential to have access to the state of the fake server, then I would suggest creating an issue/pr that describes why this is necessary and as a minimum outlines what the api could look like.
