### ISSUE TITLE
Couldn't find preset "es3" relative to directory

### ISSUE THREAD

**Issue by rdonnelly** [sinonjs/sinon#1452]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Sinon version : 2.3.2
* Environment   : node v7.10.0
* Other libraries you are using:
    "core-js": "^2.4.1",
    "normalize.css": "^7.0.0",
    "vue": "^2.3.3",
    "vue-router": "^2.5.3",
    "vuex": "^2.3.1",
    "vuex-router-sync": "^4.1.3"
    "avoriaz": "^1.15.0",
    "babel-core": "^6.24.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.2",
    "babel-loader": "^7.0.0",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-vue-jsx": "^3.4.3",
    "babel-preset-env": "^1.5.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "chai": "^4.0.1",
    "css-loader": "^0.28.4",
    "eslint": "^3.19.0",
    "eslint-config-airbnb-base": "^11.2.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^2.0.3",
    "eslint-plugin-import": "^2.3.0",
    "file-loader": "^0.11.1",
    "html-webpack-plugin": "^2.28.0",
    "karma": "^1.7.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-webpack": "^2.0.3",
    "mocha": "3.2.0",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.5",
    "sinon": "^2.3.2",
    "sinon-chai": "^2.10.0",
    "style-loader": "^0.18.1",
    "vue-loader": "^12.2.1",
    "vue-template-compiler": "^2.3.3",
    "webpack": "^2.6.1",
    "yarn": "^0.24.5"

**What did you expect to happen?**
I'm trying to test using karma and mocha. I would expect no error to pop up when I build.

**What actually happens**
```
Error: Module build failed: Error: Couldn't find preset "es3" relative to directory "/path/to/project/node_modules/sinon/node_modules/diff"
    at /path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/path/to/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/path/to/project/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/path/to/project/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/path/to/project/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/path/to/project/node_modules/babel-loader/lib/index.js:48:20)
    at Object.module.exports (/path/to/project/node_modules/babel-loader/lib/index.js:163:20)
at undefined:1
```

**How to reproduce**
Just including sinon in a spec file causes the above stack trace to pop up. I tried different versions of Sinon and other libraries to no avail. If I install the ES3 npm package, I just get to a similar, but different roadblock. Let me know what other information I can provide!

**Comment by fatso83** [comment]
There is nothing pointing this in the direction of being a Sinon issue. This seems like a babel issue - probably relating to some missing babel plugin. Try the babel project or StackOverflow.

**Comment by dwilt** [comment]
@rdonnelly did you ever fix this?  I'm running into this now trying to include Sinon in my react native project

**Comment by dwilt** [comment]
I've noticed that when I comment out Sinon, the error goes away so this sounds like an issue with this library...

**Comment by fatso83** [comment]
This isn't my responsibility to fix, but try installing `babel-preset-es3` and see if that fixes things. You might have to move it down to the right subfolder. Look at the error: it says it cannot find a babel plugin called `es3`. If you then look in `package.json` you will find `"babel-preset-es3": "^1.0.1"` as a `devDependency`. Any package in `devDependency` is *not supposed to be installed*. 

Babel seemingly looks into the `package.json` of each package in the transitive dependency graph and looks for a `babel` property. For `diff` it looks like this:
```
  "babel": {
    "sourceMaps": "inline",
    "presets": [
      "es3",
      "es2015-mod"
    ],
....
```

Now, I don't know Babel, but I assume it then tries to _use_ this information when transforming the source code, and in that case it will require the plugins (presets) to be available. They are not.

So this is, _again_, **not an issue in Sinon**, but some kind of configuration error relating to Babel. I would assume that the real bug is to be reported in the [`diff`](https://github.com/kpdecker/jsdiff) package, as I believe this shouldn't have been an issue if the package had been configured correctly. Try reporting a bug there.

**Comment by dwilt** [comment]
@fatso83 thanks for your reply. And indeed, [it is an issue with diff](https://github.com/kpdecker/jsdiff/issues/161). Solved, by installing the presets as dev dependencies.
