### ISSUE TITLE
New docs site no longer loads sinon.js itself

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sinonjs/sinon#1465]
Open Chrome and its dev tools console to, for example, http://sinonjs.org/releases/v2.3.5/. There's no `sinon` defined. There _is_ `sinon` defined in http://legacy.sinonjs.org/docs/.

Having the library loaded in the browser is super useful for folks trying out out the APIs or testing if features exist/work. Not having it is a little annoying.

If you're worried about page load time, it's reasonable to delay-load it after the page load starts. This is really just a developer convenience.

**Comment by mantoni** [comment]
This is a very good idea. I wasn't aware that we loaded sinon on the legacy page. Would you care to send a pull request to load sinon on the new page?

**Comment by mroderick** [comment]
I've been thinking about creating a sandbox page

Also, it's ridiculously easy to use JSBin, etc. We can even creat a predefined one for bug reports.

I would bet that less than 1% visits would use a sinon on the page, yet making it heavier for everyone.

**Comment by fatso83** [comment]
We could have both you know - without bloating the page. What if something like this greeted the user when she opened the DevTools console:

```
  _________.__                           ____. _________
 /   _____/|__| ____   ____   ____      |    |/   _____/
 \_____  \ |  |/    \ /  _ \ /    \     |    |\_____  \ 
 /        \|  |   |  (  <_> )   |  \/\__|    |/        \
/_______  /|__|___|  /\____/|___|  /\________/_______  /
        \/         \/            \/                  \/ 
... downloading Sinon ...
Ready! Start playing with `sinon` by testing examples here in the console. 
```

We could just [detect when the dev tools have opened](https://github.com/sindresorhus/devtools-detect) and start downloading Sinon when that happens.

-- 
Other than that I also support having a default [RequireBin](http://requirebin.com/), JSBin, or whatnot. Personal preference for [requirebin](http://requirebin.com/) since that makes it quick to import other libs.

**Comment by mroderick** [comment]
I love the idea of detecting when devtools open, and then loading sinon!

**Comment by JoshuaKGoldberg** [comment]
Problem: IE, Edge and any other browsers not supported by devtools-detect
Solution: load it immediately in those browsers only, and (just in case) have a global `loadSinon` that can be called manually?
