### ISSUE TITLE
Rename factory functions

### ISSUE THREAD

**Issue by mantoni** [sinonjs/sinon#1514]
As a follow up on #1000, what remains are the factory function renamings:

- `sinon.sandbox.create()` -> `sinon.createSandbox()`
- `sinon.fakeServer.create()` -> `sinon.createFakeServer()`

Do we want to introduce the new ones and deprecate the old ones in 4.0, and then remove the old ones in 5.0? I think this procedure worked well for the 1.x -> 3.x API transition.

**Comment by fatso83** [comment]
I like this strategy. Works, so why not continue on that way.

**Comment by mroderick** [comment]
Since we're not changing any existing behaviour, only expanding on the api (and not involving separate modules), I think we can get away with creating the new factory methods and adding deprecations to the old ones in a `MINOR` release. Then we can remove the old factory methods in the next `MAJOR` release.

**Comment by mantoni** [comment]
@mroderick Also works for me. It's just that upgrading to `^3.0.0` might have caused some deprecation warnings which the mindful developer might have fixed, and then a minor update causes more deprecation warnings. I'm personally fine with your suggestion, but it might be annoying for some people. We can add the new APIs in a minor anyway. The question is just about when to introduce the deprecation warning.

**Comment by mroderick** [comment]
Fair point @mantoni

**Comment by mroderick** [comment]
Let's add the new API and update the documentation first
