### ISSUE TITLE
[Feature request] fake constructor with stub#instantiate or something

### ISSUE THREAD

**Issue by HugoMuller** [sinonjs/sinon#1524]
Hi,

I wonder if I'm using sinon (v3.1.0) correctly, trying to stub constructors and if we can make this task simpler.

Let's say I have the following module:

```javascript
// moduleA.js

const Thing = require('Thing');
module.exports = new Thing('some', 'args');
```
I would like to fake the Thing constructor to control and spy its instances.

To achieve this, I'm doing the following:

```javascript
// unit tests of moduleA.js

const assert = require('assert');

function Thing(a, b){
  this.a = a;
  this.b = b;
}

const ThingStub = sinon.stub()
  .callsFake(() => sinon.createStubInstance(Thing));
// sinon.spy(() => sinon.createStubInstance(Thing)) can achieve this as well

const myThing = proxyquire('moduleA', { Thing: ThingStub });

assert.ok(myThing instanceof Thing);
assert.equal(myThing.a, 'some');
assert.equal(myThing.b, 'args');
```

Do you think that adding a method to sinon.stub that can achieve this makes sense?

I mean something like this:

```javascript
const ThingStub = sinon.stub().instantiate(Thing);

new ThingStub('some', 'args'); // => Thing { a: 'some', b: 'args' }
```
Let me know if I'm doing bad things, or if I can create a PR :D

**Comment by mroderick** [comment]
I prefer using a *link seam* for stubbing constructors and verifying that a function uses the expected dependencies in the expected ways.

http://sinonjs.org/how-to/link-seams-commonjs/

Is that what you meant to do?

**Comment by HugoMuller** [comment]
Yes it is.
I found this "old" [issue](https://github.com/sinonjs/sinon/issues/831#issuecomment-209648966) that lead me to this [example](https://gist.github.com/fatso83/329da40002d45533b1e74db825f2bf54). It's interesting but it doesn't demonstrate how to stub or spy an instance method.

In the following example, how can I verify that thing.doSomething is called once, with 1, 2 and 3?
```javascript
// testMe.js
const Thing = require('Thing');

module.exports = function testMe(){
  const thing = new Thing();
  return thing.doSomething(1, 2, 3);
};
````

Creating a link seam this way could be a possible solution:

````javascript
const assert = require('assert');
const sinon = require('sinon');

const doSomething = sinon.stub().returns(42);
const Thing = sinon.stub();
Thing.prototype.doSomething = doSomething;

const result = new Thing().doSomething(1, 2, 3);

sinon.assert.calledOnce(Thing);
sinon.assert.calledOnce(doSomething);
sinon.assert.calledWith(doSomething, 1, 2, 3);
assert.equal(result, 42);
````

But do you think it is a good solution?

**Comment by mroderick** [comment]
> But do you think it is a good solution?

That is certainly one way. I don't think it's any better or worse than other solutions. It has different properties. One desirable property is that you can do it without adding more dependencies to your project 😄 

With link seams, you can control exactly when the code is being loaded, or if it's loaded at all. Since some modules (especially for client side code) executes code, examines the environment and stores values **when they're loaded**, you will need to have fine control over when it's loaded in order to set up test fixtures for those.

Example:

```js
const someElement = document.querySelector('.my-element');
// ...
```

That is quite difficult to write tests for, since `someElement` will get it's value when the file is loaded, and will keep that value. Unless your test runner reloads all files between every test (I don't know of any that does this, because that would be excruciatingly slow), then you're stuck with that value for **all** your tests.

However, if your codebase is written such that no code is executed on load, but only through functions, then you can get away with not using link seams, and just use stubs.

Anyway, the merit's of link seams is a longer discussion.

Coming back to your example, we can accomplish everything you want with existing parts of Sinon.

However, we will need to ensure that we restore Thing's prototype back to its original state after each test, or **tests will become dependent on each other** and on being run in a specific order, which is a maintenance nightmare. 

We can easily ensure that everything gets restored between tests using `sandbox.restore()`;

```js
const sandbox = require('sinon').createSandbox();

describe('some test', function () {
    beforeEach(function () {
        sandbox.stub(Thing.prototype, 'doSomething').returns(42);
    });

    afterEach(function () {
        sandbox.restore();
    });

    it('should call Thing.prototype.doSomething with `1, 2, 3`', function () {
        const result = new Thing().doSomething(1, 2, 3);

        sandbox.assert.calledOnce(Thing);
        sandbox.assert.calledOnce(Thing.prototype.doSomething);
        sandbox.assert.calledWith(Thing.prototype.doSomething, 1, 2, 3);

        assert.equal(result, 42);
    });
});
```

Since we're restoring the sandbox after each test, there should be no interference with coverage calculations.

Perhaps this should all be written up as another how to article...

Do you think this is easy enough to follow? Do you think Sinon needs to be improved to better support this use case, or to make it clearer what is going on?

**Comment by HugoMuller** [comment]
Thanks for the explanation!
I didn't think about stubbing the prototype the way you did. That's quite simple actually :)
No need to improve sinon, it supports this use case well enough, as you demonstrated it.

But indeed, writing a little "How to" on this subject would help. I didn't see any example with prototype or new operator in the doc (maybe I missed it).

**Comment by HugoMuller** [comment]
I close this issue, since you answered my question :D

**Comment by hyzhak** [comment]
ok, but, how could we stub response of a contructor?
I'd like to return a custom object which on depents on passed arguments.

In a tested code I have
```
app.ask(new Suggestions(['a', 'b', 'c']));
app.ask(new Suggestions(['d', 'e', 'f']));
```
So I'd like to stub response of `new Suggestions` and return passed arguments (`['a', 'b', 'c']`, `['d', 'e', 'f']`).

**Comment by fatso83** [comment]
@hyzhak We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
