### ISSUE TITLE
Attempted to wrap send which is already wrapped occurs to run on multiple test files

### ISSUE THREAD

**Issue by samimaliks** [sinonjs/sinon#1673]
* Sinon version : =2.0.0
* Environment   : ubantu
* Example URL   :
* Other libraries you are using: Mocha, sinon, supertest, nock etc

**What did you expect to happen?**
It should not send TypeError:Attempted to wrap 'send' which is already wrapped. 
**What actually happens**
** When I run single test files it works fine, but when I run multiple test files, it stuck and gives an error on sinon.stuf('obj, 'send'').callsFake(fn); 
sandbox.stuf also used but did not work.
Note on afterEach, I restore as well. 

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

**Comment by fatso83** [comment]
@samimaliks That's not a reproducible code snippet, which means we can't do anything about it. The test says you are trying to stub a method that is already stubbed. That means you are doing something wrong. You might as well try [StackOverflow](https://stackoverflow.com/questions/tagged/sinonjs), as this is not a support forum, but a bug tracking forum.

**Comment by markpsiano** [comment]
The issue is clearly reproducible and still exists. If you understood how the library works in the slightest, you wouldn't need him to paste a code snippet for you. The library is doing something wrong by not allowing you to stub the same function across two different tests, since it runs tests in parallel. This is a major flaw with sinon. Try to be more correct, have better reading comprehension, and be less condescending next time.

**Comment by markpsiano** [comment]
Once again, you're being condescending because you don't have an actual answer to the issue at hand.

You said "Most probably he was stubbing a shared global and not cleaning up between tests."

Well, most probably, he isn't, because he didn't state that. He stated that he was stubbing something which worked fine when running the test for one file but not when adding another file stubbing the same thing. Could have been a global, sure, but nowhere did he mention not cleaning up the stub. You assumed fault on his side. This issue is reproducible even if the stub is reset at the end of every test or after every test has run, because tests run in parallel, and a parallel test can begin execution before the stub is cleaned up in another test.

"One take might be that he was writing a "synchronous" test." Well, once again, one might also take that he was NOT writing synchronous tests which were invoking async operations. Did you consider that possibility? Why are you assuming everything he's doing is wrong? Your attitude is the problem at hand. This is an issue with both sync and async tests which don't invoke async functions, or which invoke them but wait for their completion. So don't say 'well maybe' or 'one might take' that he's doing a certain extremely specific thing which might cause this to not work, because he's simply and quite obviously not.

As for being a library for providing stubbing functionality as opposed to a test runner, that's just an excuse for something that's still inherently a problem with sinon. Are you saying sinon was not designed in an extensible way where it never considered any test runner would be running tests in parallel? One workaround I found was creating a stubbing module which exports stubs of global functions, imported by separate tests, so different test files can share the same stub but still change its behavior. This is easily behavior the library can replicate. Why not provide a separate action specifically for stubbing functions shared by multiple tests? Sinon also has sandboxes simulating isolated environments, which can possibly be used to support functionality like this.

My point is, just because the library is abstracted from the test runner, it doesn't mean you shouldn't think about how it is consumed, and design with those use cases in mind. In fact, you should think critically about use cases. Thinking about use cases consumers will have is standard good engineering, whether in API design, deployments, writing libraries, clients, etc. Not doing so and blaming your users for real issues existing in the library is embarrassingly bad.
