### ISSUE TITLE
Allow custom stub implementation after initial stubbing

### ISSUE THREAD

**Issue by glenjamin** [sinonjs/sinon#169]
You can do this:

``` javascript
this.sinon.stub(object, 'method', function() { return 'MyOwnComplexThing'; })
```

But you can't do this:

``` javascript
var stub = this.sinon.stub(object, 'method');
stub.runs(function() { return 'MyOwnComplexThing'; })
```

**Comment by ahamid** [comment]
I think this would be helpful in order to supply custom funcion for mock re: https://github.com/cjohansen/Sinon.JS/issues/12#issuecomment-101843904

Since implementing this for `.returns` would be a breaking change (for existing code that returned literal functions), then an alternative could be provided (like `.runs`).
