### ISSUE TITLE
Spying on property?

### ISSUE THREAD

**Issue by natanavra** [sinonjs/sinon#1723]
Is it possible to spy on properties without ES6 getters/setters?
e.g.:
```js
let obj = {settings: {key: 'value'};
sinon.spy(obj);
sinon.assertTrue(obj.settings.key.called);
```

**Comment by Alexsey** [comment]
getters/setters are ES5 and yes, you have an option - use Proxy from ES6. But `Sinon` can help you here only by providing a `spy` that you can put in the getter to assert it later. Because `spy`s, `stub`s and `mock`s are only for functions. That is because unit testing don't imply that you should ever spy on properties

**Comment by natanavra** [comment]
OK, thanks. 
I did look for a way to check if certain properties are being "used" by a function, something like a "litmus check"
