### ISSUE TITLE
Add support for WebSockets

### ISSUE THREAD

**Issue by kmdavis** [sinonjs/sinon#174]
I have a project (and a few coworkers have projects also) that use WebSockets, and we'd like to be able to test them using jasmine and sinon in a similar manner to how we can test normal ajax.

**Comment by victorgama** [comment]
Hi everyone! Before anything, I would like to apologise for commenting on such an old issue, but I think I found a problem when executing @mantoni's snippet on Safari.

When calling `simon.stub` with `window` and `'WebSocket'` as arguments, the following exception is thrown: 
```
TypeError: Attempted to wrap object property WebSocket as function
checkWrappedMethod@sinon/pkg/sinon.js:1221:42
wrapMethod@sinon/pkg/sinon.js:1265:39
stub@sinon/pkg/sinon.js:3165:36
```

I believe this is due to the way Safari implements WebSocket. The following snippet was run on Safari 8.0.4:
```
WebSocket.prototype.constructor
=> WebSocketConstructor
WebSocket
=> WebSocketConstructor
typeof WebSocket
=> "object"
typeof WebSocket.prototype.constructor
=> "object"
```

Which causes the first assertion of the `isFunction` function fail (`typeof obj === "function"`). 
On Chrome, for instance, this does not happen:

```
WebSocket.prototype.constructor
=> function WebSocket() { [native code] }
WebSocket
=> function WebSocket() { [native code] }
typeof WebSocket
=> "function"
typeof WebSocket.prototype.constructor
=> "function"
```

I am not sure if there is a way of getting around this, hence this comment.

**Comment by JohnBaileyN** [comment]
![image](https://cloud.githubusercontent.com/assets/10504132/9697558/070c0c9c-5346-11e5-833c-6dde04ca439b.png)

**Comment by JohnBaileyN** [comment]
+1

**Comment by dmitry** [comment]
https://github.com/thoov/mock-socket - alternative implementation.

**Comment by mantoni** [comment]
I did some unit testing with the `websocket` and `sinon` modules here: https://github.com/mantoni/licy-websocket.js/blob/master/test/ws-test.js

**Comment by mroderick** [comment]
[mock-socket](https://github.com/thoov/mock-socket) is a mature library with a clean api, recommended.

**Comment by hetong-katuu** [comment]
i hope this will be helpfull:

// chat.js
const WebSocket = require('ws');

function Chat() {
  const chatSocket = new WebSocket('ws://localhost:8080');
  this.messages = [];

  chatSocket.onmessage = (event) => {
    this.messages.push(event.data);
  };
}

module.exports = Chat;

// chat.test.js
const test = require('ava');
const WebSocket = require('ws');
const Chat = require('./chat');

test.cb('basic test', (t) => {
  const mockServer = new WebSocket.Server({ port: 8080 });
  mockServer.on('connection', function (ws) {
    ws.send('test message 1');
    ws.send('test message 2');
  });

  var chatApp = new Chat();

  setTimeout(() => {
    const messageLen = chatApp.messages.length;
    t.true(messageLen == 2, '2 messages where sent from the s server');
    t.end();
  }, 100);
});

**Comment by mroderick** [comment]
I added syntax highlighting to the comment above
