### ISSUE TITLE
Returning sinon instances behaving differently

### ISSUE THREAD

**Issue by perrin4869** [sinonjs/sinon#1748]
* Sinon version : 4.3

**What did you expect to happen?**
I expected `mystub` and `mystub2` in the snippet below to behave similarly

**What actually happens**
`mystub2` behaves correctly, `mystub` behaves unexpectedly

**How to reproduce**
```
> const { stub } = require('sinon')
undefined
> const mystub = stub().withArgs(1).returns('foo')
undefined
> mystub(1)
'foo'
> mystub(2)
'foo'
> const mystub2 = stub();
undefined
> mystub2.withArgs(2).returns('bar')
{ [Function: proxy]
...
}
> mystub2(2)
'bar'
> mystub2(3)
undefined
```

I understand this is might be done by design, but I was hoping to maybe get a discussion going to change the design behind this to something more intuitive and useful in the next major release

**Comment by mroderick** [comment]
This would be a good candidate for using `git bisect` with a script to see if this was always the behaviour, or if this was changed. If the behaviour was changed, it should be easy to see from the resulting commit whether the change was intentional or not.

**Comment by perrin4869** [comment]
I could find some insight on the matter: http://nikas.praninskas.com/javascript/2015/07/28/quickie-sinon-withargs-not-working/

Basically it seems this was always the behavior...

**Comment by fatso83** [comment]
@perrin4869 This is very much related to what #1738 tried to fix and what https://github.com/sinonjs/sinon/issues/1756#issuecomment-376858756 tries to explain.

Basically, the returned object from `stub()` is not the same object that is being returned by the behaviour altering methods. #1738 should provide a more consistent behaviour, but all our tests are made using this template:

```javascript
var stub = sinon.stub();
stub.SOME_METHOD()

stub.calledWith(...)
```

That `stub = sinon.stub().SOME_METHOD()` also (sometimes) works the same is a bit unfortunate. I am thinking we should explicitly warn people not to do this. Not sure how, though, but as @mantoni says in https://github.com/sinonjs/sinon/issues/739#issuecomment-95848866:
> I can see that this is not really intuitive, but it's not a bug. Maybe it could be clarified in the docs.

**Comment by perrin4869** [comment]
@fatso83 Thanks for the clarification!
Maybe this issue should remain open until either the documentation is updated and/or a warning system is implemented?
The last thing that I would like to ask is, are there any merits to the current design over the "more intuitive" one? If changing the design is a no go, maybe a way can be added to setup behavior of spys/stubs upon creation?

**Comment by fatso83** [comment]
A merit of creating a stub first and then chaining on that is that it works consistently ... the situation we have (had) which causes mixed results when chaining inline is hard to reason around and maintain without introducing regressions, as it's dealing with a lot of mutable state.

When it comes to fixing the problem, Morgan has done some great work on the `next` branch by introducing the concept of `fakes`, which should essentially be a replacement for both spies and stubs. They are immutable by design, and will remove a lot of the current headaches. You should have a look at the [documentation](https://github.com/sinonjs/sinon/blob/c4ec3a579d2d006912af2d368ca89dd0d3d443d1/docs/_releases/v5.0.0-next.3/fakes.md) - I think it's the way to go.

With regards to tracking this, I opened #1757, to be a more specific meta-task.

**Comment by perrin4869** [comment]
Oh I didn't know about fakes, and they definitely look very promising :)

**Comment by mroderick** [comment]
@perrin4869 I published a new version yesterday, you can try it out with `npm i sinon@next --save-dev`
