### ISSUE TITLE
Build and export Sinon as an ES Module

### ISSUE THREAD

**Issue by brettz9** [sinonjs/sinon#1805]
**Is your feature request related to a problem? Please describe.**

I don't like cluttering HTML with dependencies when it is clearest to have them modularly in the particular JavaScript test files that depend on them. I don't like "magic" of not knowing where variables are supposedly coming from.

**Describe the solution you'd like**

Within each test file:

```js
import sinon from './node_modules/sinon/dist/index-es6.js';
```

or, with the following in `package.json`:

```json
"module": "dist/index-es6.js"
```
...testers could Rollup their test files with just:

```js
import sinon from 'sinon';
```

**Describe alternatives you've considered**

I could build my own module exporting this without globals but it would be a maintenance headache.

**Additional context**

Nothing.

(I would also like to see the same ES6 module option available to `sinon-test`.)

**Comment by fatso83** [comment]
Hi, thanks for chiming in. This issue is just too unclear for me. I can't see that anything is not working, and I don't understand why you use a import path that doesn't exist.

1. Depending on specific submodules within Sinon is not supported, as they're not part of the official API. Thus there is only one module to depend on, and that is the one you get when doing `import sinon from 'sinon'` today. Therefore I am not seeing how this would be any different.
2. We don't have a `dist` folder. There is a `pkg` folder.
3. We don't build an ES Module and I can't see how that would enable anything we can't do today.
4. Sinon is explicitly built to be compatible with ES5.1 engines.
5. We have talked about transpilation from ES6 (for convenience) to ES5, but found it's not worth it, both in terms of more problematic debugging and the potential performance hit you can get.

**Comment by brettz9** [comment]
Please see my comment that this is a feature request. I was just trying to fill in all the fields as far as what is "not working".

One can only use `import sinon from 'sinon'`, AFAICT, by treating it as a CommonJS plugin (and configuring this oneself rather than Sinon distributing such a version for ready consumption).

The current situation also has the disadvantage of not working out of the box in browsers that support ES6 modules--one must use Rollup to use Sinon in this manner. For testing, it is convenient to be able to just work without any build (or watch) step--just be able to work on the live code.

As far as debugging and performance, I guess that's the one issue I can't speak to, but Babel seems to be quite widely tested and employed by a great many projects.

However, in any case, a Rollup routine wouldn't need you to use Babel; like browserify, you could keep your source as is; you'd just need to change it to use `export`/`import` statements and use Rollup to bundle it into either UMD/CommonJS and ES versions.

**Comment by fatso83** [comment]
@brettz9 I took at first stab at it, but have some problems with the rollup config to make it a functional bundle. If you could take a look at the linked commit (branch) and perhaps supply a PR to fix it this can be included quickly.

Just :
```
npm run build-esm

node -r esm -e 'import sinon from "./pkg/bundle-esm"'
file:///home/carlerik/dev/sinon/bundle-esm.js:1
import typeDetect from 'type-detect';

SyntaxError: Missing export 'default' in ES module: file:///home/carlerik/dev/sinon/^Cde_modules/diff/lib/index.js
    at Object.<anonymous> (file:///home/carlerik/dev/sinon/bundle-esm.js:1)
```

**Comment by brettz9** [comment]
Sure, thanks, I'll try to take a look within the next day or so...

**Comment by fatso83** [comment]
@brettz9 This is now working on my side. See if #1809 is what you want and that it works for your html testing needs.

**Comment by fatso83** [comment]
We need to fix #1814 before cutting a new release.

**Comment by mroderick** [comment]
#1814 has been fixes, `sinon@5.1.0` is on NPM

**Comment by dpogue** [comment]
This was a breaking change that should not have been published as a minor version bump. 🙁This will cause issues for anyone using TypeScript with the @types/sinon typings (which don't expose it as an ES6 module) and WebPack (which automatically sees the `module` in package.json and uses it).

`import * as sinon from 'sinon'` no longer works at runtime in WebPack.
`import sinon from 'sinon'` works at runtime but results in TypeScript compiler errors due to the types.

Because it was a minor version, npm's default semver handling will allow it up update and result in broken (currently unfixable) builds.

**Comment by brettz9** [comment]
It is a new feature. There were no, as far as I can tell, officially documented WebPack or TypeScript usages previously, and one cannot perfectly anticipate how people may be using a library (e.g., if I have a regular expression applied to the source, I can't complain when a change in the code breaks my regular expression).

If you want to be perfectly confident in your dependencies, peg to the exact version or at least the patch version. Either that, or anticipate future additions by using "modules: false" or submitting TypeScript to the library in question so they are aware it will be breaking.

**Comment by mroderick** [comment]
I think it would it be prudent to deprecate `sinon@5.1.0` to prevent more users from being affected by this.

https://docs.npmjs.com/cli/deprecate

What do you think @sinonjs/core?

**Comment by fatso83** [comment]
sure.

**Comment by mroderick** [comment]
Done

`npm deprecate sinon@5.1.0 "This version doesn't play nice with WebPack and TypeScript"

We should revert this and put out a `5.1.1`, will you do the honours @fatso83?
