### ISSUE TITLE
Replace all document instances of stub with stub()

### ISSUE THREAD

**Issue by AndrewRayCode** [sinonjs/sinon#1884]
I'm happy to spike this in a PR. The documentation is quite confusing, since you can `import { stub } from 'sinon';`, and the docs show things like `stub.resolves()`, but you have to actually create a stub first with `stub().resolves()`. This adds a layer of cognitive complexity to newcomers!

**Comment by fatso83** [comment]
Do we really have that in our docs, though; if so, where? The reason I wonder is that we explicitly target ES5, which doesn't know that syntax. One exception: the support for using this as a ES Module. Otherwise I only know if using sinon.stub().

In any case, your fix doesn't make any immediate sense. The stub that resolves in the  example references a stub _instance_, not the exported function. I agree it doesn't make sense if it appears below an import line, in which case there should be a line creating a differently named stub first.

**Comment by AndrewRayCode** [comment]
I'm referring to things like https://sinonjs.org/releases/v6.2.0/stubs/ where all the titles are things like `stub.rejects();` - I lost some time when reading the api docs trying to figure out if I was importing `stub` wrong since it didn't have those methods

**Comment by fatso83** [comment]
Our current docs all feature numerous incantations of the form `var stub = sinon.stub();` in code preceding the examples. That's what I also call my own stubs most of the time, and I am not sure of a better name than stub for a stub. I do agree the overlap between verb and noun can be misleading. Do you have a concrete proposal for how you think this should look, generally? This is the first complain we have had in that regard, mind you, although I do know we have only had the ES6 exports feature for a few months.
