### ISSUE TITLE
stub withExactArgs

### ISSUE THREAD

**Issue by daniel-swan** [sinonjs/sinon#1933]
Would be nice to have withExactArgs for stubs.

Mocks have a withExactArgs that matches only the given arguments and no others. It would be nice for stubs to have the same behavior.

This, but for stubs:
https://sinonjs.org/releases/v7.0.0/mocks/#expectationwithexactargsarg1-arg2-

Thanks!

**Comment by mgred** [comment]
@daniel-swan There is a way of using this behavior with [`stubs`](https://sinonjs.org/releases/v7.0.0/stubs/#what-are-stubs) as well, because they implement the complete [`spies`](https://sinonjs.org/releases/v7.0.0/spies/) API you can use [`calledExactlyWith`](https://sinonjs.org/releases/v7.0.0/spies/#spycalledwithexactlyarg1-arg2-) on `stubs` to test this.

I hope this helps

**Comment by fatso83** [comment]
```
stub = sinon.stub();
stub.calledWithExactly(1,2,3) => false
```
