### ISSUE TITLE
Timeout lolex problem in integration with jest

### ISSUE THREAD

**Issue by jose920405** [sinonjs/sinon#1954]
## 🐛 Report

Hi, I have a warning related to the following message.

```
Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.633s
Ran all test suites.

Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  Timeout

      at withGlobal (node_modules/lolex/src/lolex-src.js:30:33)
      at Object.<anonymous> (node_modules/lolex/src/lolex-src.js:892:29)


  ●  Timeout

      at withGlobal (node_modules/nise/node_modules/lolex/src/lolex-src.js:30:33)
      at Object.<anonymous> (node_modules/nise/node_modules/lolex/src/lolex-src.js:858:29)

✨  Done in 3.52s.
```

It started to happen when I integrated [sinon](https://github.com/sinonjs/sinon) into my project.

#### Apparently `lolex` is the problem. Because `nise` another module that your are using, has lolex in your owns `node_modules`

Currently i'm using `"sinon": "7.1.1" and "jest": "23.5.0"`.

```
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0
```

**Comment by mroderick** [comment]
Since you provided no example code, it will be near impossible for anyone to help you determine if this is a bug or not.

We have issue templates for good reasons, please consider using those in the future.

There are only four tests in your example.  It shouldn't be too difficult to create a runnable example that demonstrates the potential bug. Once there is some code to study, it will be a lot easier for people to help you.

Thanks

**Comment by fatso83** [comment]
A minimal project would have been nice. Feel free to add a link to such a repo. Until then ...
