### ISSUE TITLE
calledOnceWith, calledOnceWithExactly

### ISSUE THREAD

**Issue by dancespiele** [sinonjs/sinon#1971]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I spy a function and I want to check if it is called once or twice with a expecific argument but if it is calling with different arguments more than one or two it will return false

**Describe the solution you'd like**
If I spy a function and it is called several time and only once with a specific argument the method `calledOnceWith` and `calledOnceWithExactly` should return true.

**Comment by mantoni** [comment]
At least `calledOnceWith` is supported by [referee-sinon](https://sinonjs.github.io/referee-sinon/#calledoncewith). We should provide consistent APIs.

I [argued against](https://github.com/sinonjs/sinon/issues/1200) this feature previously because it could be read as "called once _or_ called with arguments", but I made up my mind and now I think it's pretty clear that it means "called once _and_ with arguments".

@dancespiele Would you be interested in sending a PR?

**Comment by dancespiele** [comment]
Ok I will think more about this and I will create a PR when I have time for it, otherwise I close the ticket

**Comment by fatso83** [comment]
These method calls have always bothered me, as no matter the wording, it always ends up ambiguous.

What I would like is some kind of composition interface which makes it possible to add different matchers to make it more specific. This would make it possible to slim down the API once we have something usable. Something like our matcher API.

Not sure how it would look to avoid ambiguity, but perhaps

```
spy.calledWith(args, sinon.restrict.once)
spy.calledWithExactly(args, sinon.restrict.once)
spy.calledOnceExactly(sinon.restrict.witArgs(args))
spy.calledOnceExactly(sinon.restrict.witArgsExactly(args))
```

**Comment by fatso83** [comment]
I'll handle this issue.

**Comment by fatso83** [comment]
Both of these methods were added to the spy API last year in #1686. They have not been exposed on the separate assertion api, though.

**Comment by fatso83** [comment]
Unfortunately, their current behaviour is not at all what you wanted:
> If I spy a function and it is called several time and only once with a specific argument the method calledOnceWith and calledOnceWithExactly should return true.

They will return `true` if the method was called once in total. And when that call was made using those args. I clarified this in 49c34be0e8bcdf526ffc8c5775106db0583313ce.

FYI, what you want is almost there already: The `calledWith*` methods. They will return `true` if _one or more_ of all the calls made were made using those arguments. 

That's why I'm no fan of these multi-assert methods in general, as their naming is imprecise by nature (as I tried explaining above: a single call can have multiple interpretations). But I never managed to convince anyone the "restriction api" I proposed over was nicer to use or an improvement, so that's were it leaves us:
- use multiple assertions for precision (or)
- make sure everyone on your team knows what the assertion means
