### ISSUE TITLE
Sandbox stub variable withArgs don't match object key values

### ISSUE THREAD

**Issue by juan-carlos-correa** [sinonjs/sinon#1993]
**Describe the bug**
I want to test a property object as function passing a object param with diferent values, but the same key.

**To Reproduce**
This is the code, it is with ava as test runner.

```js
const apiKey = 'testApiKey'
const phoneNumberMx = '523121234567'
const phoneNumberUs = '19123456789'
let sandbox = null

test.beforeEach(() => {
  sandbox = sinon.createSandbox()

  UserRegisterServiceStub = {}

  UserRegisterServiceStub.getDirectories = sandbox.stub()
  UserRegisterServiceStub.getDirectories.withArgs({ apiKey, phoneNumber: phoneNumberMx } ).returns(Promise.resolve([{}]))
  UserRegisterServiceStub.getDirectories.withArgs({ apiKey, phoneNumber: phoneNumberUs }).returns(Promise.resolve([]))

  // rest of code test...
})

test.afterEach(() => {
  sandbox && sandbox.restore()
})

test.serial.cb(`${context}/tokens success test: MX phone number`, (t) => {
  // some logic of the test...
  t.true(UserRegisterServiceStub.getDirectories.called, 'UserRegisterServiceStub.getDirectories should be called')
  t.true(UserRegisterServiceStub.getDirectories.calledOnce, 'UserRegisterServiceStub.getDirectories sould be called once')
  t.true(UserRegisterServiceStub.getDirectories.calledWith({ apiKey, phoneNumber: phoneNumberMx }), 'UserRegisterServiceStub.getDirectories should be called with apiKey and phoneNumberMx')
})
```

Then:

```
UserRegisterServiceStub.getDirectories should be called with apiKey and phoneNumberMx

  Value is not `true`:

  false

  UserRegisterServiceStub.getDirectories.calledWith({
    apiKey,
    phoneNumber: phoneNumberMx
  })
  => false

  {
    apiKey,
    phoneNumber: phoneNumberMx
  }
  => {
    apiKey: 'testApiKey',
    phoneNumber: '523121234567',
  }

  phoneNumberMx
  => '523121234567'
```

Here is how i implement UserRegisterService:

`
const directories = await UserRegisterService.getDirectories({ apikey, phoneNumber })
`

And here is how getDirectories is defined:

```js
module.exports = {
  getDirectories ({ apiKey, phoneNumber }) {
    // return promise with logic...
  }
}
```

**Expected behavior**
I expected no errors

**Context**

* Library version: 7.2.3
* Environment: testing
* Example URL:
* Other libraries you are using: ava, proxquire

**Additional context**
no apply

**Comment by juan-carlos-correa** [comment]
If i remove the param as separated values, example: 

`
UserRegisterServiceStub.getDirectories.withArgs(apiKey, phoneNumberMx).returns(Promise.resolve([{}]))
`

`
t.true(UserRegisterServiceStub.getDirectories.calledWith(apiKey, phoneNumberMx), 'UserRegisterServiceStub.getDirectories should be called with apiKey and phoneNumberMx')
`

it works :o

**Comment by juan-carlos-correa** [comment]
Hello?

**Comment by fatso83** [comment]
Hi, Juan.
Sorry for leaving you hanging, but there are two issues which could answer why this was left unanswered:
1. I am not totally sure what is wrong in your issue, because it's a bit unclear. You talk about not expecting any errors, which implies there _are errors from Sinon_, but I don't see any errors anywhere in your issue.
2. The stuff I seem to understand seems like this is about a usage question. This is not the place. 

On the basis of #2, I am closing this, but if I have misunderstood and this is actually describing _a bug_ in Sinon, not a question on how to use it, feel free to comment and we'll reopen it. Be prepared to describe the points that we didn't understand in this case. So here's the usual blabla:

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by juan-carlos-correa** [comment]
Yes, you are right, this should be in stackoverflow or something like that.
