### ISSUE TITLE
sinon.restore() causes sinon.reset() not reset the history

### ISSUE THREAD

**Issue by ankanlim** [sinonjs/sinon#1996]
**Describe the bug**
Call to sinon.restore() seems to be breaking the sinon.reset() behaviour. The stubs history is not being cleared once sinon.restore is called

**To Reproduce**

Call sinon.restore() after or before sinon.reset()
stub history is not cleared
if call to sinon.restore() is removed history is cleared correctly

**Comment by fatso83** [comment]
Hi, @ankanlim. Thanks for reporting this issue.

I tried reproducing your issue, in order to understand it better. Once I managed to [reproduce it](https://runkit.com/fatso83/sinon-1996---repro), I could see why it happened, but more importantly, that this is the expected behaviour.

Click the link to run the example. The most important lines are these:
```
        sinon.restore(); // the clears the sandbox of all created fakes, stubs, etc
        assert.equals(fake.callCount, 2); // this fake is no longer associated with the current sandbox
        sinon.reset(); // resets fakes in the "new"/restored sandbox
        assert.equals(fake.callCount, 2); // this still should not affect fakes from the old sandbox
```

Check out the tests I wrote and see if they make sense to you. Closing this issue, but if I have somehow misunderstood the issue, feel free to comment!

**Comment by fatso83** [comment]
This is me playing in the REPL (`node`):

```
> sinon.getFakes()
[]
> sinon.fake()
[Function: proxy]
> sinon.getFakes()
[ [Function: proxy] ]
> sinon.fake()
[Function: proxy]
> sinon.fake()
[Function: proxy]
> sinon.getFakes()
[ [Function: proxy], [Function: proxy], [Function: proxy] ]
> sinon.getFakes().length
3
> sinon.reset()
undefined
> sinon.getFakes().length
3
> sinon.restore()
undefined
> sinon.getFakes().length
0
> sinon.fake()
[Function: proxy]
> sinon.getFakes().length
1
```

Maybe this makes some sense to you, as well.

**Comment by icsaba** [comment]
Hi @fatso83 

It seems there is an issue, or some misunderstanding around the reset method. It does not reset the stub history. I just read your example code above, unfortunately that did not help me.

i have the following code: 

` const sandBox = sinon.createSandbox();

  beforeEach(() => {
    sandBox.spy(window, 'addEventListener');
    sandBox.stub(MyClass, 'fetch'); // fetch is static
  });

  afterEach(() => {
    sandBox.reset();
    sandBox.restore();
  });
`
