### ISSUE TITLE
Why does the decoration @autobind method fail?

### ISSUE THREAD

**Issue by crycime** [sinonjs/sinon#2008]
![1555926798(1)](https://user-images.githubusercontent.com/36436659/56495321-00eadd00-6528-11e9-99a2-599d00fbbc3c.png)
![1555926859(1)](https://user-images.githubusercontent.com/36436659/56495331-0811eb00-6528-11e9-8f9b-ad233c9d6e4c.png)

**Comment by fatso83** [comment]
This issue is lacking a reproducible test case. We cannot check the validity of the issue, nor does it use a standardized syntax that I know of. Decorators are AFAIK something just usable using Babel transforms for suggested syntax. Furthermore, this smells more of a usage question than anything else.

And we do have a bug template for a reason. Closing
