### ISSUE TITLE
broken link in docs

### ISSUE THREAD

**Issue by aladdin-add** [sinonjs/sinon#2009]
![image](https://user-images.githubusercontent.com/13050025/56550403-20c9e180-65b8-11e9-80a1-a47dabab3bc7.png)

**Comment by fatso83** [comment]
This bug is not reproducible in its current form. Apart from your outline in the screenshot and the title, I have nothing to go by in this bug report. We do have a template for a reason, please use it :smiley: We need this:

**What did you expect to happen?
What actually happens
How to reproduce**

When I go to sinonjs.org and press the Documentation link it takes me to https://sinonjs.org/releases/v7.3.2. So this is not broken. Could you please elaborate?

**Comment by aladdin-add** [comment]
your link works for me. but it takes me to http://sinonjs.org/releases/v7.3.2/, and it shows:
![image](https://user-images.githubusercontent.com/13050025/56564934-ba59b900-65e1-11e9-8b38-1dd17c05a4eb.png)

seems the web does not support http?

**Comment by fatso83** [comment]
The non-SSL version works for me as well. We have automated http:// -> https:// redirect, so anything else would be surprising.

Without anything else to go by I would simply point fingers at The Great Firewall of China, as the preliminary finding is that this only applies to China. Maybe it affects other GitHub based pages as well?

**Comment by mroderick** [comment]
@aladdin-add are you still able to reproduce this?

**Comment by aladdin-add** [comment]
seems the link have been changed to https, and it's working for me, closing.
