### ISSUE TITLE
Having two withArgs on a mock won't work.

### ISSUE THREAD

**Issue by alFReD-NSH** [sinonjs/sinon#202]
``` javascript
exp = sinon.mock();
exp.withArgs(1);
exp.withArgs(2);

exp(1);
exp(2);
```

The above will throw with "Anonymous mock received wrong arguments (1), expected 2." but I expected it to not throw. Is this intended behavior? Didn't see anything about it in the docs.

**Comment by fearphage** [comment]
This is still the case in 2.3.1, but I'm not sure if it is a bug. 

@sinonjs/sinon-core Can anyone confirm?

**Comment by mroderick** [comment]
The [`withArgs` implementation for mock](https://github.com/sinonjs/sinon/blob/master/lib/sinon/mock-expectation.js#L227-L230) overwrites the expected arguments with each call.

```javascript
withArgs: function withArgs() {
    this.expectedArguments = slice.call(arguments);
    return this;
},
```

This looks very intentional to me, so I would say that it is not a bug. One might argue that it is poor design though, but that's a whole other matter.
