### ISSUE TITLE
async method from that stub when used as method.resolves(obj) cause update the obj passed as parameter

### ISSUE THREAD

**Issue by rpgeeganage** [sinonjs/sinon#2038]
**Describe the bug**
I'm not sure this is a bug or I'm missing something.

**To Reproduce**
See the code snippet.
```js
const sinon = require('sinon');
const assert = require('assert');

class GetAsyncStuff {
  async getValue() {
    return Promise.resolve({
      value: 1
    });
  }

  setValue(obj) {
    this.obj = obj;
  }
}

async function workOnStuff(getAsyncStuff) {
  for (const i of [1, 2, 3, 4]) {
    const asyncStuff = await getAsyncStuff.getValue();
    if (asyncStuff.value === 1) {
      asyncStuff.value++;
      getAsyncStuff.setValue(asyncStuff);
    }
  }
}
```

**Expected behavior**
below test case should pass, but It fails.
```js
it('this case will fail', async () => {
  const getAsyncStuffStub = sinon.createStubInstance(GetAsyncStuff);

  getAsyncStuffStub.getValue.resolves({
    value: 1
  });

  await workOnStuff(getAsyncStuffStub);

  assert.strictEqual(getAsyncStuffStub.setValue.callCount, 4);
});
```
**Screenshots**

**Context (please complete the following information):**
The only workaround I found is as follows.
```js

it('this case will pass', async () => {
  const getAsyncStuffStub = sinon.createStubInstance(GetAsyncStuff);

  getAsyncStuffStub.getValue.onCall(0).resolves({
    value: 1
  });

  getAsyncStuffStub.getValue.onCall(1).resolves({
    value: 1
  });

  getAsyncStuffStub.getValue.onCall(2).resolves({
    value: 1
  });

  getAsyncStuffStub.getValue.onCall(3).resolves({
    value: 1
  });

  await workOnStuff(getAsyncStuffStub);

  assert.strictEqual(getAsyncStuffStub.setValue.callCount, 4);
});

```
* Library version: sinon@7.3.2
* Environment: Node v10.15.3
* Example URL: 
* Other libraries you are using: Mocha@6.1.4

**Additional context**
Use `onCall(n)` is a bit unfeasible if I have a larger array or iteration. Is there any way to avoid using` onCall(n)` each time.

**Comment by fatso83** [comment]
I'm actually totally unsure what the problem is: the title is confusing and without a better description I am not totally sure how to read the code bits. I do understand what happens in the workaround ... that's about it.

It does have the smell of a usage question, though, so maybe our usual tip might be relevant?

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

---

I am guessing this is some issue with the test or code-to-be tested.

**Comment by rpgeeganage** [comment]
closing this since I need to reword the question properly.
