### ISSUE TITLE
Can Sinon stub a module that returns a function (if not, maybe a feature)?

### ISSUE THREAD

**Issue by i0natan** [sinonjs/sinon#2042]
**Is your feature request related to a problem? Please describe.**

Not exactly a problem, rather a niche scenario that is maybe supported and if not - might be a feature

**Describe the solution you'd like**

Stubbing a module that returns a function, not an object - assuming we test A, and A calls B during execution, B file/module returns to A a function (not object) which A invokes:

```
//B component code
module.exports = () =>{
//do something
}

//A code (unit under test)
require('./b.js)();
```

We want to stub B and force A to execute our double, not the real B. Is this doable with Sinon? To my humble understanding, when Sinon acts on non-anonymous functions, it expects some object+method to replace, but here we have no object (place in memory to refer to) so it can't stub it. Am I correct? does this sound like a compelling feature or beyond the scope of Sinon?

**Describe alternatives you've considered**
Proxyquire like packages that patch the 'require' method and can stub on the module level

**Additional context**
None

**Comment by mantoni** [comment]
Everything you wrote is correct and you have the right understanding of how stubbing works with Sinon. Since there are good solutions for this problem, like the mentioned proxyquire, this is what we refer to when people ask about this feature. I‘d rather not extend Sinon in this direction.

You can find more articles and libraries on this topic on our how-to page: https://sinonjs.org/how-to/
