### ISSUE TITLE
.resolves(obj) returns modified obj for subsequent calls

### ISSUE THREAD

**Issue by rpgeeganage** [sinonjs/sinon#2047]
**Describe the bug**
`stubedMethod.resolves(obj)` returns the  same `obj` as a reference. In that case, the functionality which I want to test, modify the return value of `stubedMethod.resolves(obj)`,
next call for the `stubedMethod.resolves(obj)` returns the modified object. I think it should send a new and unmodified version of `obj`.

**To Reproduce**
Please execute the following code snippet.
https://runkit.com/ruwan/5d068243c0bee1001ba1e747

**Expected behavior**
All the tests described in the above snippet should pass

**Context (please complete the following information):**
Please refer the above code snippet.

* Library version: sinon@7.3.2
* Environment: Node v10.15.3
* Example URL: 
* Other libraries you are using: Mocha@6.1.4

**Additional context**
Use `onCall(n)` is a bit unfeasible if I have a larger array or iteration. Is there any way to avoid using` onCall(n)` each time.

**Comment by slim-hmidi** [comment]
The `getAsyncStuff.setValue(asyncStuff)` will be called once : 
```
async function workOnStuff(getAsyncStuff) {
  for (const i of [1, 2, 3, 4]) {
    const asyncStuff = await getAsyncStuff.getValue();
    if (asyncStuff.value === 1) {
      asyncStuff.value++;
      getAsyncStuff.setValue(asyncStuff);
    }
  }
```
And in your test you want it to be called 4 times:
 ```
it('this case will fail - but should pass', async () => {
  const getAsyncStuffStub = sinon.createStubInstance(GetAsyncStuff);

  getAsyncStuffStub.getValue.resolves({
    value: 1
  });

  await workOnStuff(getAsyncStuffStub);

  assert.strictEqual(getAsyncStuffStub.setValue.callCount, 4);
});
```
So, it will be called once and it is the normal behavior.

**Comment by rpgeeganage** [comment]
@slim-hmidi ,
Thanks for the reply.
My problem is when we call 
``
getAsyncStuffStub.getValue.resolves({
    value: 1
  });
``
it sends the updated object from 1st iteration. which is `value:2`
(I believe because of the object reference). 
But I prefer to return same `value:1` because `getAsyncStuff.getValue()` function always resolves with a new object with value 1. (unmodifed object)
I'm sorry if my ticket and the comment is confusing.

**Comment by fatso83** [comment]
I never understood exactly what this issue was about until now, but now I see:
- you want stub#resolves(obj) to always return a superficially similar object in structure and content

That's up to you as a client to decide how you want to do, because choosing how to do that is likely to fail someones expectations, as it means you have to choose between:
- returning an immutable representation of the object a la `Object.freeze(arg)`
- not return the actual object, but cloning the original argument each time

I don't see how this is a very normal use case in any case, which indicates you should just code it yourself using the existing API. It's trivial, unless I am misunderstanding something, by just making the stub call a custom function that creates a new resolved promise each time.

```javascript
stub.callsFake( () => Promise.resolve({value: 1}) );
```
