### ISSUE TITLE
Migration guide from 6 -> 7?

### ISSUE THREAD

**Issue by toymachiner62** [sinonjs/sinon#2061]
**Describe the bug**
Is there a migration guide to go from sinon version 6 -> 7? I see there are guides for all other versions. https://sinonjs.org/releases/v7.3.2/

**Screenshots**
![image](https://user-images.githubusercontent.com/485782/61487958-b6350180-a96c-11e9-99d7-08e47ab4af08.png)

**Comment by fatso83** [comment]
Ah, well spotted. I checkd the [`semver:major`](https://github.com/sinonjs/sinon/issues?utf8=%E2%9C%93&q=label%3Asemver%3Amajor) and it seems #1926 (lolex upgrade) was the reason. Since Lolex 3 had a breaking API change (negative timers no longer possible), this validated a major release for Sinon as well.

You could also see it from the [Changelog](https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md#700--2018-10-14).

Would you like to create the migration guide and supply a PR? It's basically a one-liner, it seems :-)

**Comment by Zaky7** [comment]
Hi, I can help in this. if someone point me in right Direction. After googling I came to know after upgrading the _lolex in sinon_, we cannot **use negative timers**. So we need to avoid that. So how can I help you with the migration guide from sinon6 to sinon7 . Anything else I am missing. Or anyone else is creating a migration guide?. Please provide the link

**Comment by fatso83** [comment]
@Zaky7 Please do, that would be great!

Add a file like the others here: https://github.com/sinonjs/sinon/tree/master/docs/guides
Contributing to docs: https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md

**Comment by Zaky7** [comment]
I have created PR please Review.. Thanks

**Comment by mroderick** [comment]
This has been resolved with #2074
