### ISSUE TITLE
FakeServer - mock fetch responses in addition to xhr

### ISSUE THREAD

**Issue by jjoekoullas** [sinonjs/sinon#2082]
**Is your feature request related to a problem? Please describe.**
A request can be made to an external resource via either the xhr or fetch apis.  Refactoring an application to use the fetch over xhr is rather simple, however if sinon is used as the mocking library this requires updating mocks used in tests for this purpose.  This leads to duplicated code, especially if an application intelligently falls back to xhr in the absence of fetch.

I like the interface of fakeServer and it seems it could be agnostic of fetch vs xhr.

**Describe the solution you'd like**
fakeServer#respond calls mock both xhr and fetch responses simultaneously

**Describe alternatives you've considered**
Wrapping over sinon's fakeServer#respond methods to do this with another library.

**Comment by jjoekoullas** [comment]
I'd be happy to work on a PR if this is something the maintainers would like to add.

**Comment by mantoni** [comment]
Thank you for bringing this up. You're absolutely welcome to work on a PR for this 👍 

It would indeed be nice to be able to use the same Sinon API for both, XHR and fetch. You would have to work on [nise](https://github.com/sinonjs/nise) which is bundled with Sinon. I'll close this issue because further discussions should happen on that repository, either in your PR, or should any questions pop up, feel free to open a new issue over there.

Related issues: https://github.com/sinonjs/sinon/issues/1546 and https://github.com/sinonjs/nise/issues/7.

**Comment by jjoekoullas** [comment]
The more I've thought about this, the more it seems unfeasible without an API change.  I don't have interest in that level of change.  Sorry, I won't be sending that PR.

**Comment by eml** [comment]
For folks not doing anything particularly fancy with fetch, you can use this polyfill that translates a subset of the fetch functionality into an XMLHttpRequest:

https://github.com/developit/unfetch/blob/master/src/index.mjs

We've successfully used that with sinon's fakeServer with no problem.
