### ISSUE TITLE
Questions: are es6 modules supported?

### ISSUE THREAD

**Issue by goldbergyoni** [sinonjs/sinon#2168]
**Is your feature request related to a problem? Please describe.**
Just a question - are es6 modules supported (given that its cache is not exposed via hooks)? 

I need this info to update my testing guide here:
https://github.com/goldbergyoni/javascript-testing-best-practices

**Comment by fatso83** [comment]
Yes and no. Not sure what you mean by caching. See [this test](https://github.com/sinonjs/sinon/blob/master/test/es2015/check-esm-bundle-is-runnable.js#L9) for how Sinon is imported as a true ES module.

If you mean stubbing and spying on ES Modules , is supported the answer is that it depends. This test lists what is possible and not: https://github.com/sinonjs/sinon/blob/master/test/es2015/module-support-assessment-test.es6

The EcmaScript spec itself dictates that the _runtime_ should prevent you from modifying the ES Module, meaning the runtime (not Sinon) will throw an error if you try to do stuff such as `aModule.foo = 2` if that module had named exports like this:
```javascript
export const foo = 1;
```
and was imported like `import * as aModule from './a-module'`, where `aModule` would act as a namespace.

On the other hand, if you had an export like this:
```javascript 
export default { foo: 1 }
```
imported using `import aModule from './another-module'`, then you would have no issues mutating that export using `aModule.foo = 2`, as we are not modifying the ES Module, but the object that was exported as the default. The namespace of the Module would be unchanged.

--- 

Those rules start bending as soon as you tamper with or _simulate_ the runtime, though. For instance, if using Babel and/or Webpack, etc. to bundle ES2015+ for ES5.1 browsers, or requiring the `esm` in Node package ([like we do](https://github.com/sinonjs/sinon/blob/master/package.json#L26)). 

The behaviour of those environment, how it is done (which varies from one major version to another) and what you can do is totally unsupported from us. That doesn't mean it is not possible, just that we cannot explicitly say "Sinon supports stubbing ES Modules in Webpack", as that is a machinery in constant movement and outside of our control. We _can_ include or link to tutorials for how it's done, though.

**Comment by Farenheith** [comment]
This is an old issue, but is important to point out that **the same rules don't apply to any other software dealing with EcmaScript modules**.
**Jest** offers a pretty simple way to mock readonly modules:

```ts
const myReadOnlyFunction = jest.fn();
jest.mock('my-readonly-es6-module', () => ({
  myReadOnlyFunction,
}));
```

So, although it's not possible to modify readonly es6 exporting, there's a way to do it regardless.
But I understand that the way sinon is designed doesn't offer a way to do the same.

**Comment by fatso83** [comment]
@Farenheith Jest is a test runner like Mocha, a link level module replacement tool like proxyquire, a stubbing framework like Sinon, an assertion lib like Chai and a whole lot of other things. It's not really comparable, as being that tightly integrated with Node and its own tooling means it can do a bunch of thing other standalone libs cannot. It can for instance use custom module loaders that hook into Node to allow mocking of ESM. This integration also restricts what it can do, as that mocking of modules won't work when the code under test does not run inside of Node (like spinning it up in a real browser using Karma instead of not-quite-a-browser tools like JSDom).

If you want a buildless way of developing modern software without lots of frameworks that also allow mocking ESM you should check out [Modern Web](https://modern-web.dev/docs/test-runner/writing-tests/mocking/), as they have an interesting take on how to approach module mocking (intercepting it at the web server level, before it gets passed to the runtime). I am thinking of using that approach for creating a Vite plugin to allow per-test mocking.

**Comment by trusktr** [comment]
Where's the ESM code? All I see are CommonJS files. For example:



> you should check out [Modern Web](https://modern-web.dev/docs/test-runner/writing-tests/mocking/), as they have an interesting take on how to approach module mocking (intercepting it at the web server level, before it gets passed to the runtime). I am thinking of using that approach for creating a Vite plugin to allow per-test mocking.

To expand on that, the approach is simply just standard [JavaScript import maps](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap). With that you can map any impot specifier to any URL (f.e. to import from a file that has mocks instead of the real thing).

**Comment by fatso83** [comment]
For people coming here and wondering how to approach stubbing ESM, the guide I wrote as a case study on how to approach this (using SWC+Typescript+Mocha) could be worth looking at: [Case study: real world dependency stubbing
](https://sinonjs.org/how-to/typescript-swc). I list up 4 different approaches to achieving this (some more generic than others), along with a general recipe for figuring out how things are transpiled (if at all) in your environment, and how you can use this to find the right approach.
