### ISSUE TITLE
Browser script contains Nodejs module require statements

### ISSUE THREAD

**Issue by charlesmulder** [sinonjs/sinon#2169]
**Describe the bug**
`./node_modules/sinon/pkg/sinon.js`, which according to documentation is meant for direct browser use, contains Nodejs module require statements.  

**To Reproduce**
```sh
cat ./node_modules/sinon/pkg/sinon.js
```

**Expected behavior**
`./node_modules/sinon/pkg/sinon.js` should be pre-bundled for browsers. No calls to `require()`.

**Context (please complete the following information):**

* Library version: 7.5.0

**Comment by fatso83** [comment]
This issue report does not actually list any problems arising in any runtime, which is not strange, given that it seems it has not been tested in any browser that shows a problem 😉 If you are new to how bundling CommonJS modules works, then I can understand seeing `require` calls in the code might cause confusion. The important thing here is that we have _not created a Node project_. We have created a library composed of modules following the CommonJS way of creating modules. This was introduced by Node, but there are tools (such as WebPack and Browserify) that introduce shims (small alternative implementations) that makes the same code work when bundled together. So when we say the code works in all browsers, it is because we know they do, testing them daily 😸 

You might find the [homepage for Browserify](http://browserify.org/) and [our build script instructive](https://github.com/sinonjs/sinon/blob/master/build.js#L23).

**Comment by fatso83** [comment]
You might also be interested in this issue: #2168

**Comment by charlesmulder** [comment]
Thanks for the response. So, before including `./node_modules/sinon/pkg/sinon.js` in my browser, I should bundle it with Webpack or Browserify?

**Comment by fatso83** [comment]
I am not saying any such thing. You can do exactly as it says. This is a modification of Mocha's docs, as a more feature complete example.
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Mocha Tests</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://unpkg.com/mocha/mocha.css" />
  </head>
  <body>
    <div id="mocha"></div>
    <script src="https://unpkg.com/chai/chai.js"></script>
    <script src="https://unpkg.com/mocha/mocha.js"></script>
    <script src="https://unpkg.com/sinon/pkg/sinon.js"></script>

    <script class="mocha-init">
      mocha.setup('bdd');
      mocha.checkLeaks();
    </script>

    <script src="test.array.js"></script>
    <script src="test.object.js"></script>
    <script src="test.xhr.js"></script>
    <script class="mocha-exec">
      mocha.run();
    </script>
  </body>
</html>
```

`/pkg/sinon.js` _is_ the bundle. We do that for you.

**Comment by fatso83** [comment]
Do feel free to supply a PR with changes to our docs!
https://github.com/sinonjs/sinon/blob/master/docs/CONTRIBUTING.md

**Comment by charlesmulder** [comment]
Consider me enlightened. Much appreciated.
