### ISSUE TITLE
Documentation for restore()

### ISSUE THREAD

**Issue by 76784** [sinonjs/sinon#2176]
If my understanding is correct, `sinon.restore()` has been deprecated in favor of `object.method.restore()` For example, this would be correct: `jQuery.ajax.restore()`.

If the above is correct, then this page still shows `sinon.restore()` (see "Default sandbox" section):
https://sinonjs.org/releases/v7.5.0/sandbox/

**Comment by fatso83** [comment]
No, this is a misunderstanding. While individual stubs can be reset, it is usually more convenient to use a sandbox to restore them all at once. Sinon's stubs/spies/fakes are created in a default sandbox instance to make this feature available by default. That means, instead of doing

```javascript
var sandbox;
before(){
  sandbox = sinon.createSandbox();
}
afterEach(){
  sandbox.restore();
}
it('uses spies', function() {
   var spy = sandbox.stub(foo, 'somemethod');
   // do something with foo.somemethod()
});
```

you can now do 


```javascript
afterEach(){
  sinon.restore();
}
it('uses spies', function() {
   var spy = sinon.stub(foo, 'somemethod');
   // do something with foo.somemethod()
});
```

Feel free to suggest ways of improving this difference :-)
