### ISSUE TITLE
Unable to stub es6 modules after webpack v4 upgrade

### ISSUE THREAD

**Issue by bgp1** [sinonjs/sinon#2280]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.
I used to use Webpack v3 and have several thousand JS unit tests. I stub modules so that I can assert they are called as expected without actually executing the module code. Since upgrading to Webpack v4 the stubs no longer stub. The code is executed and I cannot assert that something was called once or read the arguments passed in the stub. 

* Sinon version : 9.0.2
* Environment   : Windows 10 x64
* Example URL   :
* Other libraries you are using: webpack, mocha, babel

**What did you expect to happen?**
I expect my unit tests to work the same. I stub my modules and can assert they were called.

**What actually happens**
The stub does not actually stub so may unit tests are broken. 

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

**Comment by bgp1** [comment]
```
import * as login from '../../account/login';
import * as tracking from '../../modules/tracking';

describe('account/login.js', function() {
    it('login.trackLogIn() should call the trackEvent() method once on submit', function() {
        const stub = sinon.stub(tracking, 'trackEvent');

        login.trackLogIn();
        assert.equal(true, stub.calledOnce);
        assert.deepEqual(['user', 'login'], stub.args[0]);

        tracking.trackEvent.restore();
    });
});
```

In this example prior to the upgrade this test passed. Now it no longer stubs the code so the first assert returns false and the second assert is deeply comparing my array to undefined.

**Comment by mroderick** [comment]
I suspect that the observed behaviour is because Webpack v4 is more compliant with ESM than Webpack 3. With ESM you're not supposed to be able to modify imports.

However, because you're using `import * as tracking from '../../modules/tracking'`, Sinon isn't capable of identifying `tracking` as an ESM module, and doesn't give you a warning when you're working against the grain.

Dependency mocking is out of scope for Sinon.

Webpack 4 was released on February 25, 2018 ... more than two years ago.

I am sure there are userland solutions to mocking dependencies with Webpack 4.

---

We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question, please post it to the [`sinon` tag on Stack Overflow](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions.

If you feel that your topic is an issue with Sinon.JS itself, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue). A **runnable** example (git repostiroy, gist, codepen) would help speeding up a correct diagnosis of the issue experienced.
