### ISSUE TITLE
A very basic fs stub fails with typescript and ts-node. 

### ISSUE THREAD

**Issue by mohitt** [sinonjs/sinon#2296]
**Describe the bug**
I am trying to stub `existsSync` method of fs module and have written a very basic test for it. Is there anything I am doing wrong ? 

**To Reproduce**
1. Go to https://github.com/mohitt/isolate-sinon
2. Clone and run `npm run test`
3. You will see a test failure. Ideally speaking that test should not fail. 

Following is the test https://github.com/mohitt/isolate-sinon/blob/master/fs.test.ts 
```
import chai from 'chai';
import sinon from 'sinon';
import * as fs from 'fs';
import chaiAsPromised from 'chai-as-promised';

chai.use(chaiAsPromised);

import { expect } from 'chai';


describe('readConfigFile', () => {
  it('returns Fallback value if file is not there - @FileNotThere', () => {

    sinon.stub(fs, 'existsSync').returns(true);
    expect(fs.existsSync('something')).true;

  });
});
```
I am using `typescript` and `ts-node` with `mocha`. 

**Expected behavior**
The test should pass once the `existsSync` is stubbed using `Sinon.stub`. `existsSync` should always return true. 

**Screenshots**

**Context (please complete the following information):**

* Library version: _please verify that the bug exists in the latest release_
* Environment:
* Example URL:
* Other libraries you are using:

**Additional context**

**Comment by rgroothuijsen** [comment]
To my knowledge, Sinon doesn't support stubbing imported modules.

**Comment by mohitt** [comment]
I have seen an example of something like this. https://github.com/sinonjs/sinon/issues/458 . I just tried migrating that example to `ts-node` and typescript.

**Comment by fatso83** [comment]
We are trying to keep the GitHub issues list tidy and focused on bugs and feature discussions. This ticket looks like a usage question; please post it to [StackOverflow](https://stackoverflow.com/questions/tagged/sinon) and tag it with [`sinon`](https://stackoverflow.com/questions/tagged/sinon), so the bigger community can help answer your questions. 

If you feel that your topic is an issue with Sinon, please open a new ticket and follow the [guidelines for reporting an issue](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md#reporting-an-issue).
---
@mohitt Since you are using Typescript you are actually not using ES Modules (which is not possible without transpilation, see #2258). That means that what you are trying is probably possible, assuming it's transpiled to ES5 or something like that. The way to go about this is to attack it like you are working with ES5. So inspect what the resulting code looks like in Javascript after transpilation and work with that. You need to account for all kinds of weird stuff like module loaders, webpack, esm, etc. yourself, because the environment is different from project to project. Sinon only works with normal javascript and does not try to capture imports and interfere with the runtime. That is what tools like `proxyquire` is for.

People on SO are usually quick to answer Sinon questions, btw. I also monitor the tags from time to time.

**Comment by uchia-itachi** [comment]
any update on how we could stub fs in typescript using sinon ?

**Comment by fatso83** [comment]
@uchia-itachi Typescript is only Javascript in the end, so there is nothing inherent about TS that makes this any different than any non-TS project. As mentioned above:

>  Sinon only works with the normal javascript runtime and does not try to capture imports and interfere with the runtime. That is what tools like proxyquire, Jest, etc is for, as they change the runtime in order to do "magic" stuff. This is all totally different from project to project, so we cannot do much about this.

So answering your question will depend on how your project is setup. Does it transpile to ES5.1 with synthetic getters, does it create actual ESM, does it use Vite, does it use Webpack, does it use Jest, etc. There is no general answer to this. _You_ need to look into what the Javascript you want to test looks like and choose tools accordingly. 

If you use Jest, for instance, it will change the runtime in order to allow to capture all calls for modules. If you run using Vite, this all goes out the window and you need to find some other way of doing things. If I were you I would create a minimal project on GH that mimicks your existing project structure and ask a question on Stack Overflow, linking to that. Good luck!
