### ISSUE TITLE
Sinon stub silently fails on the getter

### ISSUE THREAD

**Issue by pyrocat101** [sinonjs/sinon#2334]
**Describe the bug**

When calling `sinon.stub` on a property getter that returns a function, sinon **silently** fails.

**To Reproduce**

Try the following code snippet with sinon@9.2.3:

```js
const realObject = {
  get foo() {
    return () => {
      console.log('real foo');
    }
  }
}

const sinon = require('sinon');

sinon.stub(realObject, 'foo').callsFake(() => {
  console.log('fake foo');
});

realObject.foo();  // <-- prints "real foo"
console.log(realObject.foo.getCalls());  // <-- TypeError: realObject.foo.getCalls is not a function
```

**Expected behavior**

Either one of these:
1. Property `foo` is stubbed by the fake that prints `"fake foo"`.
2. Sinon throws an error indicating that `foo` cannot be wrapped / stubbed.

**Context (please complete the following information):**

* Library version: 9.2.3
* Environment: Node v15.3.0
* Example URL: N/A
* Other libraries you are using: N/A

**Comment by fatso83** [comment]
This actually works fine. Not your code, though, but the API you need to use works fine 😸 Try https://sinonjs.org/releases/latest/stubs/#stubgetgetterfn

This shows it working.
https://runkit.com/fatso83/600613e3c12f8a001a30760f

**Comment by pyrocat101** [comment]
@fatso83 Thanks for the reply. I am aware of the `stub.get` API, but this issue is more about the usability:

I am using sinon stubs for testing in a large codebase and ran into this "silently failing" behavior. It takes me quite some time to finally track down where the code under test uses the property getter.

That is why I am proposing changing the behavior of `stub` to throw an error about the misuse, instead of silently failing to stub the property. Would you reconsider?

**Comment by fatso83** [comment]
@pyrocat101 This is definitively an issue from the user perspective, but how would you suggest that this works (not the implementation details, but the API)? I cannot see this working using the existing API. We cannot default to throwing if `stub(obj, 'prop')` turns out to try and wrap an accessor method, because we need to not throw in able to do `stub.get(newFake)`.

This is basically why we added the much cleaner [`sinon.replace*()` API](https://sinonjs.org/releases/latest/sandbox/#sandboxreplaceobject-property-replacement). By dropping the chainable nature in the Stubs API we get more verbose, but easier to understand tests.
