### ISSUE TITLE
CERT_HAS_EXPIRED certificate has expired is thrwon when I'm trying to update sinon package

### ISSUE THREAD

**Issue by DaniRvd** [sinonjs/sinon#2406]
**Describe the bug**
sinon versiom 1.17.16
CERT_HAS_EXPIRED  is thrown when I'm trying to run the pipeline for my web app.
In the pipeline I have a step bower install wen all packages are installed but when it try to install sinon , the pipeline is failing with CERT_HAS_EXPIRED  error
I tried to update form local with the  command  **_bower update sinon_** but I have the same result
**To Reproduce**

1. Go to 'cmd'
2. paste  '**_bower update sinon_** '
3. Run
4. See error CERT_HAS_EXPIRED  

**Expected behavior**
Sinon update should be made without any error

**Screenshots**

**Context (please complete the following information):**

- Library version: _please verify that the bug exists in the latest release_
- Environment:
- Example URL:
- Other libraries you are using:

**Additional context**
![image](https://user-images.githubusercontent.com/20532118/135977677-c422e6f4-18c5-4ba9-adee-39d5db272709.png)
![image](https://user-images.githubusercontent.com/20532118/135977757-ed9c973b-f9ec-401d-9ce9-5c1be14e9e0b.png)

**Comment by fatso83** [comment]
Thanks for filing a bug, but we cannot really do much about how the package is distributed in your setup. We do not support Bower (which is woefully outdated and deprecated for the last 6 years) and we only publish the Sinon package to the homepage and NPM. No other places. The certificate must come from something within the Bower setup, as we only control sinonjs.org, and that certificate is valid until Dec 4 2021.

It is _extremely_ easy and not time consuming at all to transition your setup to using NPM instead of Bower, so I would start doing that, instead of trying to fix this bower issue. If you cannot be bothered to update references to your bower scripts one simple alternative is to simply create a small script (Bash, Node, whatever) that copies the scripts from their locations in `node_modules` to their location today. Then add that to your `package.json` as the `"postinstall"` script:
```json
...,
"scripts": {
  "postinstall": "./copy-npm-deps-to-bower-location.sh",
}
```
