### ISSUE TITLE
Feature request: Expose sinon as global on website for quick testing

### ISSUE THREAD

**Issue by mokkabonna** [sinonjs/sinon#2414]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Expose latest sinon as a global on the sinon website for quickly testing features of it in the developer console. This is a quick and simple way to test something without installing it via npm or CDN.

Ideally with a log statement printed that sinon is exposed when you open the console.

**Describe alternatives you've considered**
Either I have to download it and run it locally via some code that imports the module or run it on websites like runkit. Both of these alternatives are quite slower than just pressing F12 and playing with it in the console.

**Additional context**
Many websites for js libs expose their own library as a global on the website, like lodash (as _ ), vue, react.

This is proably in the category of nice to have, but well, it *would* be nice to have :)

----------

Thanks for a great library, been using it for years! It was of great assistance to get started with serious js testing years ago.

**Comment by fatso83** [comment]
We talked about this years ago, and it is a relatively quick win, so if anyone put in the minutes to add it, then that would surely be accepted. I am sure it would be enough to add a a small `<script module ..../>` reference to the default Jekyll template, where the script either referenced one of the locally scripts or a SkyPack version.

P.S. You might have seen already, but we have runnable examples on the documentation. Like here: https://sinonjs.org/releases/v12.0.1/spies/. This is editable in the browser and runs via RunKit. It is lacking on some pages, but that is only because no one has put in the effort to complete this for every doc page.

**Comment by fatso83** [comment]
Did not appear for some reason. Will verify before closing.

**Comment by fatso83** [comment]
Verified to be working
