### ISSUE TITLE
Keep track of url query parameters in sinon fake server

### ISSUE THREAD

**Issue by yuliacech** [sinonjs/sinon#2416]
**Is your feature request related to a problem? Please describe.**
I'd like to test which exact query parameters were used for requests to the sinon fake server. In my app, those parameters correspond to pagination, sorting and filtering parameters. For example, for page 1 of a list the request would be `my_api/my_list?pageSize=20&pageIndex=0` and for page 2 of the same list it's `my_api/my_list?pageSize=20&pageIndex=1`.

**Describe the solution you'd like**
I'd like to be able to access the query parameters via `server.query` or alternatively via `server.url`. Currently, for both request the url value is the same `server.url: my_api/my_list`. 

**Describe alternatives you've considered**

**Additional context**

**Comment by fatso83** [comment]
Hi, @yuliacech . You probably long since have your answer, but AFAIK this should already be possible by just having a look at the Request object? All requests are available on the Server object, see https://github.com/sinonjs/nise/blob/master/lib/fake-server/index.js#L169.

This is also mentioned in the [docs for `nise`](https://sinonjs.github.io/nise/#fake-server) (used internally by Sinon), but I am not sure if this is reflected in the actual docs for the "mother project" (it should be):

```
        const server = fakeServer.create();
        server.respondWith("GET", "/some/article/comments.json",
            [200, { "Content-Type": "application/json" },
             '[{ "id": 12, "comment": "Hey there" }]']);

        var callback = sinon.spy();
        myLib.getCommentsFor("/some/article", callback);
        server.respond();
        const req = server.requests[0] // <--- should contain your XMLHttpRequest
        req.url // <-- what you are looking for?
```

From browsing the code (https://github.com/sinonjs/nise/blob/master/lib/fake-xhr/index.js#L502) it just seems like we assign the url without parsing it or modifying it in any way, so it should just be `req.url`.


If I am mistaking what you ask for, you could just reply :)
