### ISSUE TITLE
Stub does not work when running in parallel and inside a promise

### ISSUE THREAD

**Issue by lukasholzer** [sinonjs/sinon#2440]
**Describe the bug**
when running in parallel (like with ava) and having two tests that are each stubbing a function they are working in a sync mode.

But once the test is using some async code the stubbing does not work.

**To Reproduce**

Checkout this stackblitz example: https://stackblitz.com/edit/node-fwnyqb?file=README.md

**Expected behavior**
Stubbing in async mode should work exactly the same as in sync mode

**Screenshots**

![CleanShot 2022-01-31 at 12 00 44](https://user-images.githubusercontent.com/11156362/151782316-33b915e0-f286-4dae-8a30-d9ce86e3223c.png)

**Context (please complete the following information):**

Can be all seen inside the stackblitz example:

**Comment by fatso83** [comment]
If Ava is legit running tests in parallel, then of course we can do nothing. This is up to you and the testrunner, as that's why you usually refrain from doing this for exactly this reason. You need a way if running them sequentially. This is why a parallel runner like Jest will create new Node processes for each test suite, exactly to avoid global pollution between test suites. It runs the individual tests in sequence, ofc

**Comment by lukasholzer** [comment]
Thx for the reply running in serial does fix the issue! @fatso83 thx for your help :)
