### ISSUE TITLE
Jest got a new mock 

### ISSUE THREAD

**Issue by Biki-das** [sinonjs/sinon#2443]
https://github.com/facebook/jest/pull/12285

**Comment by fatso83** [comment]
**This issue is lacking relevant information, preventing it from being worked on**

---

The reason we have an [issue template](https://github.com/sinonjs/sinon/blob/master/.github/ISSUE_TEMPLATE.md) is for issues to have sufficient detail  to be able to be worked on.

This issue lacks some or all of the information needed for us to do something meaningful about it.

We usually ask for this to be provided:

* Sinon version :
* Environment   :
* Example URL   :
* Other libraries you are using:

**What did you expect to happen?**

**What actually happens**

**How to reproduce**
> Describe in sufficient detail how to reproduce the faulty behaviour for the person that should choose to work on the problem

<details>
    <summary>Really long code sample or stacktrace</summary>

    If you need to provide a dump of a stack trace or
    other lengthy material, such as 80 lines of example code,
    please stuff it in a `<details>` tag such as this
    to make the issue more readable. Thanks.
</details>

**Comment by fatso83** [comment]
Ah, I checked out the link. You implemented `lastCall` for Jest. Good for them 😄
