### ISSUE TITLE
Nested stub accepts all arguments and returns only first definition

### ISSUE THREAD

**Issue by xxSkyy** [sinonjs/sinon#2447]
**Describe the bug**
Doing simple nested object with stubbed function at the end makes it matching all values when stubbed in "defining chain" but otherwise it works.

**To Reproduce**
 
This configuration doesn't work as supposed to
```js
    const app = {}

    app.db = {}

    app.db.users = sinon
      .stub()
      .withArgs({ id: 1 })
      .resolves({ username: "foo" })

    app.db.users
      .withArgs({ id: 2 })
      .resolves({ username: "other foo" })

    const result = await app.db.users({ id: 1 })
    console.log("User: ", result)
// User:  { username: 'foo' }

    const result1 = await app.db.users({ id: 2 })
    console.log("User: ", result1)
// User:  { username: 'foo' }
    
    const result2 = await app.db.users({ id: "anything or empty" })
    console.log("User: ", result2)
// User:  { username: 'foo' }

```
but this one do work
```js
    const app: any = {}

    app.db = {}

    app.db.users = sinon.stub()

    app.db.users.withArgs({ id: 2 }).resolves({ username: "foo" })
    app.db.users.withArgs({ id: "anything" }).resolves({ username: "bar" })

    const result = await app.db.users({ id: 1 })
    console.log("User: ", result)
// User:  undefined

    const result1 = await app.db.users({ id: 2 })
    console.log("User: ", result1)
// User:  { username: 'foo' }

    const result2 = await app.db.users({ id: "anything" })
    console.log("User: ", result2)
// User:  { username: 'bar' }

```

**Expected behavior**
First example should behave as second exemple

**Context (please complete the following information):**

- Library version: 13.0.1
- Environment: Node 16.13.1, Apple M1 MacOS 12.2.1
- Other libraries you are using: mocha, chai, nyc, typescript, sinon-mongo-ts

**Comment by fatso83** [comment]
Your second example is [how we document using it](https://sinonjs.org/releases/latest/stubs/#stubwithargsarg1-arg2-). 

In essence, this is a recurring issue with chained API's, which is why we created the much simpler-to-reason about Fakes API.
The problem is that when you do this: `.withArgs({ id: 1 }).resolves({ username: "foo" })` you are creating a new/different stubs instance than what you were working on. Getting the changes propagated down to the original was a constant source of confusion bugs and people always would wonder about what the `this` pointer would point to. In essence: this is working as intended, although we know it is not optimal.
