### ISSUE TITLE
Bug mocking with SWC

### ISSUE THREAD

**Issue by assertnotnull** [sinonjs/sinon#2528]
**Describe the bug**
Sinon is unable to mock the function when compiled with SWC but works with ts-node

**To Reproduce**
clone [the sample repo with bug
](https://github.com/assertnotnull/sinon-swc-bug)
```
pnpm i
pnpm test
```
Outcome:
```
1) main
       should mock:
     TypeError: Descriptor for property toBeMocked is non-configurable and non-writable
      at assertValidPropertyDescriptor (node_modules/.pnpm/sinon@15.2.0/node_modules/sinon/lib/sinon/stub.js:138:15)
      at Function.stub (node_modules/.pnpm/sinon@15.2.0/node_modules/sinon/lib/sinon/stub.js:89:5)
      at Sandbox.stub (node_modules/.pnpm/sinon@15.2.0/node_modules/sinon/lib/sinon/sandbox.js:389:39)
      at Context.<anonymous> (src/main.spec.ts:12:22)
      at processImmediate (node:internal/timers:476:21)
```

To see it working with ts-node replace "@swc/register" with "ts-node/register"
Then run pnpm test again and it passes.

**Expected behavior**
It should mock

**Comment by fatso83** [comment]
This is _clearly_ not an issue with Sinon, but with your transpiler tooling. It even says clearly what the issue is: 
> Descriptor for property toBeMocked is non-configurable and non-writable

While ts-node clearly exports a writeable [object descriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor), SWC does not. This is in-line with _how ES Modules are supposed to work_, so SWC seems to be the correct behavior here.

Just googling "swc writable object descriptor" comes up with [a few suggestions](https://stackoverflow.com/a/72793194/200987), some ok workarounds. I would still try another approach, if you just need to do this to have mutable namespaces for your modules, and that is to use the [Dalton's ESM loader](https://www.npmjs.com/package/esm). It has an option to make namespaces mutable and you can register it before your SWC module.

**Comment by assertnotnull** [comment]
I've tried the suggestion in stackoverflow as I also found this before but it's not working either.
Other libraries complexifies the tests too much that it outweighs the benefits.
I guess running tests with mocks is not an option with SWC.

**Comment by fatso83** [comment]
You can use [mocks in the original sense](https://martinfowler.com/bliki/TestDouble.html), but nowadays mocking is more colloquially used as a term for intercepting loading of dependencies and replacing those with some test double (stub, fake, mock, dummy). That was easier when "everyone" was using derivatives of the CommonJS module system, either in Node or using some bundler like Browserify or Webpack. This was because the importing of other modules happened at _runtime_, so you could `if/else` different dependencies at runtime or hook into the module loading like `proxyquire` and similar did. This changes in 2015 when ES Modules were introduced, as they are resolved earlier and cannot be programmatically replaced like we used to, except if you do stuff to the runtime like Jest is doing; essentially transpiling everything to `require` calls . This is why we essentially had issues like this from 2015 (see #831, for instance).

# Solutions

## Replace module loader
Once you are in _true_ ESM land (not transpiled to ES5 and/or CJS), you cannot mutate exports in the normal runtime. For that to be allowed, you need to hook into the process _earlier_, by replacing the _module loader_. This is actually been allowed in Node for _ages_ (Node 13?) and used by various tools. One alternative to Sinon is TestDouble, which has most of the basic functionality of Sinon, but it _also_ bundles its own module loader for use with ESM! You can either go all in on that, or just use the module loading.

Here's the link for documentation on how to use this (it's quite painless): [td.replaceEsm()](https://github.com/testdouble/testdouble.js#tdreplace-and-tdreplaceesm-for-replacing-dependencies)
You basically just need to supply an extra flag for node to use TD's module loader, and it should work. TD has very few dependencies, but one of them is Quibble, which is actually the library responsible for doing the module replacement. So you could alternatively [just use that directly](https://www.npmjs.com/package/quibble#user-content-es-modules-support):
```
node --loader=quibble ...
# or mocha --loader=quibble ...
```

then
```javascript
  await quibble.esm('./a-module.mjs', {life: 41}, 'replacement universe');
```

Check the docs. 

P.S. By now, I actually cannot remember if using SWC results _actual ES Modules_ (which have immutable namespace) or something else (seeing the object descriptor thingies above. Sorry. I have the memory of a goldfish), so this might or might not work for your 🤷 If it turns out the resulting transpiled code is not ESM you can just use `proxyquire` ([Sinon guide](https://sinonjs.org/how-to/link-seams-commonjs/)).

## Alternative to hooking into the link layer: pure dependency injection
[Pure dependency injection](https://blog.ploeh.dk/2014/06/10/pure-di/) (previously called "poor man's DI") is something I often reach for to avoid complicating my setup. You get a slight change in production code to enable better tests. You can see my describing a fuller example of this in https://github.com/sinonjs/sinon/issues/831#issuecomment-198081263

Issues related to ESM stubbing: #831, #1623, #1711, 
Issues related to CJS stubbing: #1248, #1648

**Comment by fatso83** [comment]
P.S. I have some extra time today, so thought I might as well try getting this working. Testing out Quibble now.

**Comment by fatso83** [comment]
Working fine! I forked your repo and got it working: https://github.com/fatso83/sinon-swc-bug/tree/cjs-mocking

Be aware, that this is relying on CommonJS modules. At first, I configured Quibble to do ESM replacements, but I was not able to get it working. The problem was that this was never ESM to begin with. Your `.swcrc` file explicitly specifies that the module system should be CommonJS. Furthermore, I found that [the defaults for the SWC configuration](https://swc.rs/docs/configuration/compilation) targets ES5. Once I figured that I was really just working with CJS it took just a minute to get it working:

```javascript

  before(async () => {
    mocked = sandbox.fake.returns("mocked");
    quibble("./other.ts", { toBeMocked: mocked });
    const mainModule = require("./main");
    main = mainModule.main;
  });

  it("should mock", () => {
    main();
    expect(mocked.called).to.be.true;
  });
```

P.S. This is the first time I have used Quibble (TestDouble). You could just as well have used Proxyquire, which is what we suggest in [our how-to for replacing modules](https://sinonjs.org/how-to/link-seams-commonjs/).

**Comment by fatso83** [comment]
Another approach is of course to just modify the output of SWC. The `jest-workaround` plugin for SWC does just this, so I opened https://github.com/magic-akari/jest_workaround/issues/65 to ask if it was possible to re-use this in other test runners. That would make it re-usable in Ava, Mocha, etc. 

The issue with non-mutable exports is the same for Webpack and other transpilers, for that matter.

**Comment by fatso83** [comment]
# Some notes

I looked into how to configure a TS project into using an ESM (not-CommonJS module transpilation) based approach and ran into one problem: when [configuring TypeScript to produce ES Modules](https://www.typescriptlang.org/docs/handbook/esm-node.html), you need to specify file extensions in your imports (not a problem). You also need to make Node aware how the `ts` extension is to be handled when loading modules, as you will otherwise get `TypeError: Unknown file extension ".ts" for /Users/myuser/code/sinon-swc-bug/src/main.spec.ts`. That is usually handled by setting `--loader=ts-node/esm`, but you _also_ need Quibble to be used as the loader for module replacement to work! While there is [a project in Node dedicated to add support for using multiple loaders](https://github.com/nodejs/loaders#purpose), this is not complete, so you cannot use two loaders today.

As you can currently only specify a single loader, you would then need to implement a custom loader that did the juggling of making the output of `{ load, resolve }` in one loader work together with the same ones from another loader. I stumbled over [this example](https://github.com/cucumber/cucumber-js/issues/1844#issuecomment-1110836603), which could be used as a starting point. I do not intend to do that right now 😄 

So if using SWC, I would configure your TS project to use CJS for the time being, if possible and just use the approach I showed above (in the [`cjs-mocking` branch](https://github.com/fatso83/sinon-swc-bug/tree/cjs-mocking)).

If you do not need TypeScript and just need to generally stub ESM, I put a working ESM example in the 
[esm-no-ts branch](https://github.com/fatso83/sinon-swc-bug/tree/esm-no-ts).

https://github.com/fatso83/sinon-swc-bug/tree/cjs-mocking

**Comment by fatso83** [comment]
@assertnotnull Did you see the workaround I provided for you? Was just wondering if that worked fine, as I was thinking of updating the old link seams article with examples for modern bundlers/transpilers, as this comes up quite a bit.

**Comment by fatso83** [comment]
I was also thinking that it might be useful to have error messages point directly to relevant docs? So instead of "Descriptor for property toBeMocked is non-configurable and non-writable" change it to something like 
> The descriptor for the property `toBeMocked` is non-configurable and non-writable. Sinon cannot do anything about this, as it is essentially immutable. Read https://sinonjs.org/faqs#immutable-objectdescriptor for tips on what could cause this and how to possibly resolve it.

(The link is made up by the way).

**Comment by assertnotnull** [comment]
Thank you @fatso83 for spending much time looking into this. I find this is quite complicated to use different loaders, specially if such change was applied to a big project but the last solution is interesting. I will give it a try.

**Comment by fatso83** [comment]
Good to hear from you! I did write that article in the end, btw, but no-one has commented and reviewed my PR. I should contain all the details one could need. Would you have a chance at reviewing it to see if this looks useful for people?

**Comment by assertnotnull** [comment]
The changes https://github.com/fatso83/sinon-swc-bug/tree/swc-with-mutable-exports works!
I only had to modify the definition of mocks in the `beforeEach` and add the plugin!
![image](https://github.com/sinonjs/sinon/assets/821567/59666cf1-fffc-4b27-a5f1-26e13a967642)

**Comment by assertnotnull** [comment]
I must add, this is in a Nestjs project where Jest has been replaced with Mocha + Sinon. We faced memory leaks with Jest in the past.

**Comment by DanKaplanSES** [comment]
> Here's the link for documentation on how to use this (it's quite painless): [td.replaceEsm()](https://github.com/testdouble/testdouble.js#tdreplace-and-tdreplaceesm-for-replacing-dependencies)

Worth noting this function errors (with a helpful message) if you use jest as your test runner.

**Comment by fatso83** [comment]
On that note, I just found out that it is indeed possible to use multiple loaders with Mocha (as in both swc and quibble). See https://github.com/testdouble/quibble/issues/101

**Comment by piotracalski** [comment]
Hello 👋  I would like to bump this thread and share our experiences in dealing with this issue.
We're using:
- `mocha`: 9.2.2
- `sinon`: 15.2.0
- `@swc/core`: 1.6.5

We've recently migrated our _Mocha_ and _Sinon_ test suite from _babel_ to _swc_. We obviously started to experience problems similar to what has been already described in this thread, meaning: _sinon_ mocks stopped working and we were unable to run our test suite. Because we're operating in a large monorepo with thousands of test files, when solving this issue all methods which involved making changes to the test code (e.g. described in [this sinon blog post](https://sinonjs.org/how-to/typescript-swc/)) didn't seem like the right choice for us. Ultimately, the way to solve this problem we decided on was to:
- add a new setup file for Mocha to deal with immutability of properties generated by swc when compiling module exports (based on an example taken from [here](https://github.com/magic-akari/swc_mut_cjs_exports/issues/103#issuecomment-1926819722)),
- patch _sinon_ using `patch-package`, to provide support for ES module _get accessors_ generated by _swc_.

This allowed us to use _swc_ for tests using _sinon_ without the need to modify any of the test code.
As mentioned above, we're currently using `sinon@15.2.0` but while working on our solution we made sure that the full _sinon_ test suite passes locally with our changes. That said, if we re-opened this issue I could try to apply our patch for the latest version of _sinon_, which could potentially provide support for _swc_ to other _sinon_ users.

**Comment by fatso83** [comment]
@piotracalski Thanks for taking the time to post your solution. I am sure that could prove helpful.

> all methods which involved making changes to the test code (e.g. described in [this sinon blog post](https://sinonjs.org/how-to/typescript-swc/)) didn't seem like the right choice for us

I described _three different categories_ in that article
1. Mutating the output from the transpiler ([updated example code](https://github.com/fatso83/sinon-swc-bug/tree/swc-with-mutable-exports) that I just tested to be working with Node 22)
2. Change your code to be tooling independant by using pure dependency injection to provide collaborators
3. Replace the module loader to be able to intercept and return a different module ([updated example code](https://github.com/fatso83/sinon-swc-bug/tree/cjs-mocking))

What you are describing is basically the first approach + adding some tooling specific patch to avoid needing to change test code to deal with the accessors specifically. I love that you found a way of making Sinon run the code without altering the test code. Still, I don't like _magic_, especially in test code, as the abstraction never fails to break at some time.

We cannot add tooling specific code to Sinon's core. That just is not a scalable approach. How the module systems you are dealing with works has so many permutations: (number of tsconfig options affecting transpilation) x (transpiled) TS or JS) x (ESM or CJS) x (Node <= 20.5 or Node > 20.5) x (# of different transpilers).

We cannot support that complexity without a dedicated staff updating all the examples and support code, as this seems to change all the time. The only scalable approach is giving teaching people to fish, which is what [the article you referred to](https://github.com/fatso83/sinon-swc-bug/tree/swc-with-mutable-exports) really is about. And given that you found a workaround, I guess it works 😉 

We could _perhaps_ see what options there are for allowing third-party plugins to modify the Sinon runtime to do whatever your patch is doing (assuming you are replacing `sinon.stub` with `sinon.replaceGetter` or modifying `sinon.stub` directly?), by opening up for some kind of injection point. Maybe you could post the link and we can see if there is some way of making it work if published as `@pietro/sinon-swc-esm-to-cjs-support`?

**Comment by piotracalski** [comment]
Thanks for taking the time to respond to my post 👍 your approach seems reasonable to me.
for informative purposes, I created _sinon_ repo fork, reverted it to `@15.2.0` and made an example PR with the changes which worked for us: https://github.com/piotracalski/sinon-patch-for-swc/pull/1
