### ISSUE TITLE
Iterating over Readable streams never resolves with fake timers

### ISSUE THREAD

**Issue by mattdean-digicatapult** [sinonjs/sinon#2619]
**Describe the bug**

With sinon v19 and using fake timers `Readable` streams will never resolve. This causes tests that need to evaluate the contents of `Readable` streams to timeout. Now it might be I shouldn't expect this to work as I am doing async stuff, but this did work with sinon v18 so for now I'd at least consider this a bug. 

**To Reproduce**

1. setup a fake timer using `sinon.useFakeTimers` or similar
2. try to read all the data from a Readable
3. The final chunk of the Readable will never resolve

I've created a reproduction repo of this https://github.com/mattdean-digicatapult/usefaketimers-bug-reproduction if you'd like to test it out. The test code is as follows:

```js
import { Readable } from "node:stream";

import { expect } from "chai";
import { before, describe, it } from "mocha";

import sinon from "sinon";

describe("sinon bug reproduction", function () {
  let result;

  before(async function () {
    const clock = sinon.useFakeTimers({ now: 100 });
    const stream = Readable.from(Buffer.from("test"));
    const chunks = [];
    for await (const chunk of stream) {
      chunks.push(chunk);
    }
    result = Buffer.concat(chunks).toString("utf8");
    clock.restore();
  });

  it("should run successfully", function () {
    expect(result).to.equal("test");
  });
});
```

**Expected behavior**

The stream to finish reading as occurred in sinon v18

**Screenshots**

![Screenshot 2024-09-13 at 10 15 38](https://github.com/user-attachments/assets/2099ef26-4618-49a5-8dd5-dc057388ab6b)

**Context (please complete the following information):**

- Sinon version : v19.0.0
- Runtime: nodejs 22

- Other relevant environmental info: macos
- Other libraries you are using: Mocha, Chai (see reproduction for versions)
- Example URL: https://github.com/mattdean-digicatapult/usefaketimers-bug-reproduction

**Additional context**

None

**Comment by fatso83** [comment]
I am guessing this is related to us now faking all timers by default in version 13 of Fake Timers: https://github.com/sinonjs/fake-timers/blob/main/CHANGELOG.md#1300--2024-08-25

Somehow the underlying code you are using might depend on `nextTick()` or `queueMicroTask()`. See what happens if you explicitly set the `toFake: [... ` array of timers to fake.

Ref https://github.com/sinonjs/fake-timers/pull/323

**Comment by fatso83** [comment]
Great testcase. Was exactly what I assumed. This fixes your issue:
```
-    const clock = sinon.useFakeTimers({ now: 100 });
+    const clock = sinon.useFakeTimers({ now: 100, toFake: ["setTimeout"] });
```

**Comment by fatso83** [comment]
@SimenB This might be a side-effect you can be aware of in Jest. Not sure how we should document this.

**Comment by fatso83** [comment]
Just to add some info. It's the `nextTick()` timer that never resolves. Instead of explicitly saying you _don't_ want to fake that, you could also of course use `runToLastAsync()` and use the fact that this is dealing with async work.

I pushed a "fix" to your example: https://github.com/fatso83/usefaketimers-bug-reproduction/commit/54c812d

Hope that helps!

**Comment by fatso83** [comment]
I'll add this as a note to the migration guide: https://sinonjs.org/guides/migration-guide. Thanks!
