### ISSUE TITLE
useFakeTimers does not work with lodash because of cached copies

### ISSUE THREAD

**Issue by travi** [sinonjs/sinon#343]
Related: https://github.com/lodash/lodash/issues/304

lodash provides a _.runInContext to allow configuration of the context, but I have not been able to get it to work with fakeTimers. If anyone could get this to work, it would be great if sinon was able to handle this case so that others don't get stuck on this problem.

**Comment by Offirmo** [comment]
On this subject, lodash author recently (may 2016) made a gracious move of no longer caching some functions :

* comment https://github.com/lodash/lodash/issues/2054#issuecomment-220152292
* PR https://github.com/lodash/lodash/commit/84b8ee7bdace8ea4d6a34fe00f6df85c8b2d4cb6

There is still an issue with Date.now(), which may be solved from sinon/lolex size. I'm working on it.

**Comment by fatso83** [comment]
Now that `lolex` uses `now = function() {return Date.now}`, why is there still an issue?

**Comment by islemaster** [comment]
I think it's because [the main lodash export calls `runInContext`](https://github.com/lodash/lodash/blob/4.13.1/lodash.js#L16376) which [closes over a bunch of globals including `Date`](https://github.com/lodash/lodash/blob/4.13.1/lodash.js#L1234).  Even after lolex replaces window.Date, lodash is referring to the version it closed over.

You could solve this by installing lolex once before requiring any production code, but at least in the tests I'm currently working on that's not a great solution; I'd rather install lolex before each test and uninstall it afterward.  You could also use `runInContext` directly and inject a modified lodash into everything under test, but I'm not a fan of that either.  If someone has a better solution I'm all ears.

**Comment by basecode** [comment]
I wonder why lodash closes over `Date` but not `setTimeout`?

```js
setTimeout = function(func, wait) { return context.setTimeout.call(root, func, wait); };
```

vs

```js
function now() {
  return Date.now(); // mocking would work with `context.Date.now()`
}
```

**Comment by islemaster** [comment]
I'm not sure; the only thing I can guess from the comments is because it's a constructor, but that shouldn't make a difference here (and `new Date()` is never called within lodash as far as I can tell).

Actually, `now()` is the only usage of the closed-over `Date` and there are only four usages of `now()`.  This seems like a straightforward change.  Shall we propose it over at lodash/lodash?

**Comment by islemaster** [comment]
Whoa! It's like @jdalton is watching us - he just added support for this in (as-yet-unreleased) https://github.com/lodash/lodash/commit/14845416e3986201d28d01195484770429b7d56d

I pulled master and did a quick test - this works like a charm!

```javascript
  it('can stub clock for debounce', function () {
    var clock = lolex.install();
    var spy = sinon.spy();
    _.debounce(spy, 1000)();
    expect(spy.callCount).to.equal(0);
    clock.tick(1);
    expect(spy.callCount).to.equal(0);
    clock.tick(998);
    expect(spy.callCount).to.equal(0);
    clock.tick(1);
    expect(spy.callCount).to.equal(1);
    clock.uninstall();
  });
```

Thanks @jdalton!

**Comment by Offirmo** [comment]
Thanks @jdalton! Thanks +10000
