### ISSUE TITLE
expectation.with[Exact]Args cannot be used with onCall

### ISSUE THREAD

**Issue by tgr** [sinonjs/sinon#472]
var o = {f:function(){}},
        mock = sinon.mock(o);
    mock.expects('f').twice()
        .onFirstCall().withArgs('a').returns(1)
        .onSecondCall().withArgs('b').returns(2);

Expected behavior: creates a mock which will verify that `o.f` was called twice, first with `'a'` and second with `'b'`. The first `o.f` call returns 1, the second returns 2.

Actual result: throws an error about how `withArgs` must be called before `onCall`. That is for `stub.withArgs` though, which is a completely different function - I would expect to be able to invoke `expectation.withArgs` here.

    var o = {f:function(){}},
        mock = sinon.mock(o);
    mock.expects('f').twice()
        .onFirstCall().withExactArgs('a').returns(1)
        .onSecondCall().withExactArgs('b').returns(2);

Expected behavior: Like before, except more strict about the arguments.
Actual behavior: throws error about `withExactArgs` not existing.

**Comment by mroderick** [comment]
I find this ticket somewhat confusing.

Are you reporting defects with existing implementation, or stating that the API doesn't meet your expectations?

**Comment by yang** [comment]
At least for me (encountering the same limitation as described above), the API doesn't meet expectations.

**Comment by mantoni** [comment]
This is intentional, as the exception suggests.

The only "bug" here is that `withExactArgs` should throw a similar error as `withArgs`, because we can't / don't want to support this kind of chaining.

I would recommend removing the `withArgs` parts and instead add a verification that the calls were made with the expected arguments. Your example is somewhat mixing stub programming and expectation verification.

**Comment by yang** [comment]
The desired fluency is something along the lines of the following, which if
memory serves is the mode of certain other mock libs like gmock:

On the first call, ensure that the args are X and return Y
On the second call, ensure that the args are W and return Z

Anyway, this ticket is not a huge deal since one can achieve the same
ensure checks with the post-hoc assertions (calledWithArgs).

(While we're on this topic, I'm also curious about the statement in the
docs that no test should involve more than one mock object—is there further
reading on this?  Esp. given that one can achieve the same results using
spies post-hoc?  I assume the underlying message is something different
from simply OAPT.)
