### ISSUE TITLE
Sinon FakeServer Creation 

### ISSUE THREAD

**Issue by hsbafna** [sinonjs/sinon#560]
Hi,  
     I am trying to run sinon using jasmine in karma.But i am getting an error of fakeserver is undefined.I am indcluding the fakeserver.js file from  sinon,Can anyone please help me out. I am working on windows 7

**Comment by mroderick** [comment]
@blazer916 I am having difficulties understanding how to reproduce this issue.

Do you still have this issue? 

If so, could you perhaps create a runnable example that demonstrates the issue in a gist, jsfiddle, jsbin or similar? Or provide more context on how you run this code in order to make it fail.
