### ISSUE TITLE
Proposal: Argument snapshots

### ISSUE THREAD

**Issue by BigstickCarpet** [sinonjs/sinon#665]
[Other](https://github.com/cjohansen/Sinon.JS/issues/571) [issues](https://github.com/cjohansen/Sinon.JS/issues/583) have already been raised about the fact that Sinon stores arguments by reference, which means they can be changed between the time the spy is invoked and the time we assert on it.   Per @mroderick, the decision seems to be that this is by-design and storing arguments by value would cause all sorts of other problems. 

Agreed.  But I have a proposal that could work for everyone.   Leave the current `spy.args` property as it is (by reference), but add a `spy.snapshot` property that contains [deep clones](https://lodash.com/docs#cloneDeep) of each argument _at the time the spy was invoked_.   Here's an example:

``` javascript
function changeName(person) {
    person.name = 'Billy Bob';
}

var spy = sinon.spy(changeName);
spy({name: 'John Doe'});

// spy.args is by-reference, so the "name" property has been changed
assert.equal(spy.args[0][0].name, 'Billy Bob');
assert.equal(spy.firstCall.args[0].name, 'Billy Bob');

// spy.snapshot is by-value, so the "name" property is as it was when the spy was called
assert.equal(spy.snapshot[0][0].name, 'John Doe');
assert.equal(spy.firstCall.snapshot[0].name, 'John Doe');
```

**Comment by cjohansen** [comment]
It's not a bad idea, but it would still be a leaky abstraction. For instance, `_.cloneDeep(document.body) === document.body`. I'm not sure, @mantoni @mroderick?

**Comment by mantoni** [comment]
I like the first part about storing both. But we could solve the assertion bits in a different way:
How about we do the assertions as they are, but if one fails, we use the snapshot as a fallback. The assertion would only fail if both, the reference and the clone are unequal.
What do you think?

**Comment by BigstickCarpet** [comment]
@cjohansen - Granted, `_.cloneDeep` isn't a _perfect_ snapshot in all cases.  In fact, in [LoDash 3.0](https://github.com/lodash/lodash/wiki/Changelog#v300), it no longer clones some DOM objects (e.g. `_.cloneDeep(document.body) !== document.body`), so we'd have to do a shallow clone of those objects (e.g. `_.extend({}, document.body)`)

@mantoni - That fallback approach would work for Sinon's built-in asserts (e.g. `sinon.assert.calledWithMatch({name: 'John Doe'})`), but not for third-party assertion libraries (e.g. `chai.expect(spy.firstCall.args[0].name).to.equal('Billy Bob')`)

**Comment by mantoni** [comment]
True. But it would also work with `calledWith` and friends.

**Comment by BigstickCarpet** [comment]
Ah, I see what you mean.  I like it!!   Both `sinon.assert.calledWith` and `spy.calledWith` would use the fallback, and devs could still explicitly use `spy.args` or `spy.snapshot` if they didn't want the fallback functionality.

**Comment by cjohansen** [comment]
I'm intrigued, but I'm still a little skeptical of the potential of being too clever. Let's play devil's advocate: what's the worst thing that can happen if we go this route?

**Comment by BigstickCarpet** [comment]
Playing devil's advocate...  there will still be some confusing behavior with this proposal.  But there's already confusing behavior currently, and I'd argue that the current behavior is more confusing than the proposed behavior.

````javascript
var spy = sinon.spy(console.log);
var obj = {name: 'John Doe'};
spy(obj);

// Current behavior (this would remain unchanged)
// ----------------------------------------------------------------------------
assert.isTrue(spy.calledWith(obj));                             // Intuitive
assert.isTrue(spy.calledWith({name: 'John Doe'}));              // Intuitive
assert.isTrue(spy.calledWithMatch({name: 'John Doe'}));         // Intuitive
assert.isTrue(spy.firstCall.args[0].name === 'John Doe');       // Intuitive

obj.name = 'Billy Bob';    

// Current behavior (this would be changed)    
// ----------------------------------------------------------------------------
assert.isTrue(spy.calledWith(obj));                             // Intuitive
assert.isFalse(spy.calledWith({name: 'John Doe'}));             // Confusing !!
assert.isFalse(spy.calledWithMatch({name: 'John Doe'}));        // Confusing !!
assert.isFalse(spy.firstCall.args[0].name === 'John Doe');      // Confusing !!

assert.isTrue(spy.calledWith({name: 'Billy Bob'}));             // Confusing !!
assert.isTrue(spy.calledWithMatch({name: 'Billy Bob'}));        // Confusing !!
assert.isTrue(spy.firstCall.args[0].name === 'Billy Bob');      // Confusing !!

// Proposed behavior    
// ----------------------------------------------------------------------------
assert.isTrue(spy.calledWith(obj));                             // Intuitive
assert.isTrue(spy.calledWith({name: 'John Doe'}));              // Intuitive
assert.isTrue(spy.calledWithMatch({name: 'John Doe'}));         // Intuitive
assert.isTrue(spy.firstCall.args[0].name === 'John Doe');       // Intuitive
assert.isTrue(spy.firstCall.snapshot[0].name === 'John Doe');   // Intuitive

assert.isTrue(spy.calledWith({name: 'Billy Bob'}));             // Still Confusing !!
assert.isTrue(spy.calledWithMatch({name: 'Billy Bob'}));        // Still Confusing !!
assert.isTrue(spy.firstCall.args[0].name === 'Billy Bob');      // Still Confusing !!
assert.isFalse(spy.firstCall.snapshot[0].name === 'Billy Bob'); // Intuitive
````

**Comment by mantoni** [comment]
There are 3 combinations that can occur:

1) References are equal, result is `true`. That is the current behavior already.
2) References are not equal, deep clone is not equal as well, result is `false`. That matches the current behavior as well.
3) References are not equal, deep clone is equal, result is `true`. This is the new case.

What can lead to the third scenario? I can see two cases where the deep equals comparison of the original object and the clone would fail:

1) The case that we are trying to address, where the original object got modified.
2) The clone is for some reason unequal to the original object right from the start. Maybe a circular reference or whatever clever things are going on in native objects ... I don't know.

We need to be confident enough about the deep clone to work reliably or detect when it does not, so that we don't introduce new false alarms, I guess.

@BigstickCarpet Good examples. Helps to clarify. This would need some explanation in the docs. I'm personally never using the `args` arrays because I think they don't read particularly nice. It's more like an internal thing to me. Hoping that most people use the more expressive APIs.

**Comment by cjohansen** [comment]
@mantoni your second point was the one I was worried about. But is there any situations where that will screw up any of todays behavior, given that we keep `args` around?

**Comment by mantoni** [comment]
If we put the feature in and all the tests are still green ... ;-)

**Comment by mantoni** [comment]
Or we play it safe and only add it on the 2.x branch.

**Comment by mroderick** [comment]
This is a very interesting discussion!

I like the snapshot idea, as it's very clear what is going on. It says so **right there in front of you**, there's **nothing** to be confused about. (One might name them `clonedArgs` or `args.snapshot`).
Further, it can be documented to hell and back what the limitations of `snapshot` are.

However, I am not so sure about the fallback idea for `calledWith` and friends, as that is basically the same idea as previous tickets have proposed, but implemented using `snapshot`, leaving `args` alone.

Here's some more devil's advocate.

##### Currently
1. To more experienced JavaScript programmers, it would be obvious (perhaps with minor effort) to see why `calledWIth` might fail when you pass objects to the spy and then update them. 
2. Less experienced JavaScript programmers will be confused, until they learn what pass by reference really means for JavaScript, and become more experienced programmers. See 1

##### Proposed scenario for `calledWith`
1. More experienced programmers will be confused that `calledWith` accepts the previous state of the spy's argument object(s) as they have clearly modified it since the spy call. They might start to question the design decisions in Sinon.JS, and wonder what other places there are odd design decisions (like I do, when reading the source of the ever so popular clientside MVC libraries).
2. Less experienced JavaScript programmers will accept things as they are presented to them. Eventually they will learn about pass by reference in JavaScript and thus become more experienced JavaScript programmers. See 1

If we do decide to change how `calledWith` and friends work, we should put out a new MAJOR version (`v2.0`), since this will change the meaning of the API.

No matter which direction we take, I think there's room for improvements to the documentation, as people seem to struggle with this area of testing.

**Comment by cjohansen** [comment]
Thanks for your input guys. I agree with almost everyone, so hard to make a decision :) Ultimately, I think that `calledWith` should return `true` if you give it an object-literal equal to whatever it received at call-time, call-by-reference or not.

Here's my suggestion:

1. Shoot a PR for adding `args.snapshot` to master
2. When it's done, I'll rebase 2.x with master
3. Shoot a PR to boost `calledWith` and friends in 2.x
4. We solicit feedback with a 2.x-pre build

**Comment by mroderick** [comment]
:+1:

**Comment by freethejazz** [comment]
I like the idea, but getting deep cloning right is more about drawing a line about where it breaks more than getting it to work all the time.
```
var MyClass = function(opts) { this.opts = opts; };
MyClass.prototype.getOpts = function() { return this.opts; };

var a = new MyClass('foo');
var spy = sinon.spy();

spy(a);

assert.equals(spy.firstCall.args[0].getOpts(), 'foo'); // true
assert.equals(spy.firstCall.snapshot[0].getOpts(), 'foo'); // undefined is not a function
```

I think the ability to clearly describe expected behavior and where the line is drawn for deep cloning is really important, like @mroderick and @mantoni suggested.

**Comment by mroderick** [comment]
Is there still traction for this issue, or can we close it?

**Comment by rmtsukuru** [comment]
Was anything discussed in this thread ever implemented? Not having some way when writing unit tests to confirm the value of object parameters _when they were passed in_ to a function call seems like an important feature, even if it requires storing that data in a separate place from the args list (which is fine by me, although having calledWith pull from both would also be great).

**Comment by mantoni** [comment]
There have been attempts to implement this, but it’s very hard to make copies of objects in a reliable way. Especially when you think of class instances and circular dependencies. It’s a can of worms. If you want to try as well, feel free :)
