### ISSUE TITLE
sinon-timers-1.15.4.js not possible to use standalone

### ISSUE THREAD

**Issue by CodeOfficer** [sinonjs/sinon#793]
the code path for running sinon standalone (without AMD and not in Node) ends up calling makeApi(sinon) ... ignoring the 2nd argument ... which sets llx to undefined and then tries to call llx.install ....

BOOM

**Comment by mroderick** [comment]
This probably hasn't worked since `lolex` was extracted to it's own module about a year ago.

@cjohansen @mantoni, I think we should stop building `sinon-timers` as an independent module, and update the documentation (http://sinonjs.org/docs/#clock) to encourage people to use [lolex](https://github.com/sinonjs/lolex) directly, if they want fake timers without using Sinon.JS

**Comment by mroderick** [comment]
@CodeOfficer thank you for reporting this!
