### ISSUE TITLE
Remove sinon-timers from build

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#811]
`lolex` was extracted to it's own module about a year ago, it's time to stop packaging `sinon-timers` as an independent module and encourage people to use it's successor `lolex` instead.
- [x] Stop generating `sinon-timers.js` into `pkg/`
- [x] Update [clock documentation](http://sinonjs.org/docs/#clock) and point to using `lolex` for standalone fake timers without Sinon.JS

**Comment by evdb** [comment]
On http://sinonjs.org/download/ the links under "Stand-alone fake timers" 404 - which I think is related to this issue as the code is no longer being generated?

**Comment by pimterry** [comment]
How are built lolex packages for the browser supposed to be made available in future?

Since the Sinon.js download page now has a 404, as you're no longer building sinon-timers within Sinon, I went to look at the lolex package itself and the release notes there say "if you want to use Lolex in a browser, you have a few options. Releases are hosted on the sinonjs.org website". Feels like that just sends you back round in circles. It works if you're using NPM of course, but not everybody will be.

Are you going to have a download site for lolex, or some other release mechanism over there? At the moment these files are just completely unavailable (although you can just guess URLs to get an old version of course).

**Comment by mantoni** [comment]
@pimterry Yes, we need to think about how we package standalone versions. Sorry for the confusion. In the meantime, you can use the [lolex.js](https://github.com/sinonjs/lolex/blob/master/lolex.js) file.

**Comment by mroderick** [comment]
This has been implemented with https://github.com/grassator/Sinon.JS/commit/5ee643df517f6ed7296b4a1ce0a81317949526d6

**Comment by mroderick** [comment]
@pimterry the browserified version of `lolex` is available via npm. Do you still think people will want to download this manually?

**Comment by pimterry** [comment]
Hard to say whether others will want this, but that sounds fine to me personally.

**Comment by mroderick** [comment]
@pimterry I've created an issue for the direct download of lolex.js
