### ISSUE TITLE
assert.calledOnceWithMatch

### ISSUE THREAD

**Issue by magnars** [sinonjs/sinon#84]
`assert.match` is the best thing way before sliced bread, and I want it with everything. But most of all I want it with `assert.calledOnceWith`. 

The usecase that prompted this issue was todays snafu:

```
fs.createReadStream(__dirname + '/blank-config-file.js');
```

stubbing out this so-and-so makes for some unwieldy `getCall` and `args` incantations. Sinon is for beauty, and let me tell you - this code I just wrote isn't gonna win any pageants. :)

**Comment by meetmangukiya** [comment]
Wouldn't `calledOnceWithMatch` imply one more assertion that it was called only once? In which case `calledWithMatch` is not the same as `calledOnceWithMatch`.

**Comment by mantoni** [comment]
Called once with match is on the way: https://github.com/sinonjs/sinon/pull/2294

**Comment by meetmangukiya** [comment]
awesome!

**Comment by fatso83** [comment]
@meetmangukiya The assertions that check two things are ambiguous. That's why I do not use them. We had this discussion multiple times: `calledOnceWithMatch ` could mean 
- the spy was called one or several times, and of those calls, it was _at least_ one call that matched.
- the spy was called one or several times, and of those calls, exactly one single call matched.
- the spy was called exactly one time and that single call matched.

Of course, if you check the docs, you know :)

We do have the `calledExactly*` methods as well. If you want to be precise for the casual reader, I'd just do two assertions.

**Comment by mantoni** [comment]
Since we do have these combined assertions now, I tend to always read them as "and" expressions of the underlying assertions. They're basically short hands to fold two assert calls into one. That's a rule we should stick with for consistency, I think.
