### ISSUE TITLE
sinon-ie not working with IE11 (win 7)

### ISSUE THREAD

**Issue by epikhighs** [sinonjs/sinon#848]
So I did some debugging and for some reason if I emulate IE 10 and below, then the code in sinon-ie.js works as intended.  However, if I use IE 11, then the following code returns an 'Object doesn't support property' error, where getTime is not defined on Date

`(new Date()).getTime()`

The entire prototype chain of Date is just a plain object without any of the Date specific methods.  All the global methods and classes that sinon-ie tries to override has this problem in IE11.  For example, the following will not work as well in IE11.

`setTimeout(function () {console.log(2)}, 500)`

Not sure why emulating IE 10 and below works though.  Has anyone else encountered this?

Thanks.

**Comment by mroderick** [comment]
Let's see if I've understood your description correctly.

When `sinon-ie.js` is loaded in IE11, then `(new Date()).getTime()` throws an Error. But, when emulating IE10 in IE11, it doesn't?

Does it work when `sinon-ie.js` is not loaded?

Perhaps we should recommend people to only use `sinon-ie.js` for IE10 and below, or use conditional comments in `sinon-ie.js`.

Suggestions welcome

**Comment by timwienk** [comment]
I can confirm this issue on both IE11 and Edge (12), I ran into this problem today (or actually a few days ago already, but we upgraded more than just sinon, it just took a while to figure out what the hell was going on). It appears indeed to be the case that all global methods and classes set in `sinon-ie.js` cause problems. The `setTimeout`-like functions don't do anything (no errors either, just nothing) and the constructor functions have no prototype chain. Example errors below (collected with Karma):

Calling a Date method:
```
IE 11.0.0 (Windows 10 0.0.0) ERROR
  Object doesn't support property or method 'getTime'
```
Calling an XMLHttpRequest method:
```
IE 11.0.0 (Windows 10 0.0.0) ERROR
  Object doesn't support property or method 'setRequestHeader'
```

As a last resort kind of thing, and while eliminating as many things as possible, I compared the previous version of `sinon-ie` we used to the version I was trying to use. It turned out that the only actual changes are the `if (typeof window !== "undefined")` conditionals around the different pieces of code. In the spirit of _"whatever remains, no matter how improbable, must be the truth"_ I proceeded to remove these conditionals.

Yes, indeed, removing these conditionals solved the problem. I have no idea what the actual reason is this happens (I suspect it must have to do with some weird kind of caching/optimising IE tries to do), but apparently these conditionals _do_ have practical effect (#840).
