### ISSUE TITLE
Example XHR response throws error

### ISSUE THREAD

**Issue by jmeas** [sinonjs/sinon#864]
**Version:** 1.17.1
**Problem:** Error in docs

**More details:**

The example response [given in the docs here](http://sinonjs.org/docs/#server):

``` js
this.requests[0].respond(200, { "Content-Type": "application/json" },
                                 '[{ "id": 12, "comment": "Hey there" }]');
```

Throws the following error when you try to use it:

`Error: Invalid responseType blob`

The stack trace leads me to [this line](https://github.com/sinonjs/sinon/blob/f8091656c6da4411cf25aeaeef6327405bd10356/lib/sinon/util/fake_xml_http_request.js#L335).

I'm trying to figure out how to make it not explode, but I haven't used Sinon's fake XHR before now, so I'm digging through the source to see what it wants me to set, and where.

I'd be happy to a PR to update the docs if anyone can point out what's missing :)

Thanks for reading!
# 

Updated:

I tried to set the `responseType` explicitly:

``` js
this.requests[0].responseType = 'json';
this.requests[0].respond(200, { "Content-Type": "application/json" },
                                 '[{ "id": 12, "comment": "Hey there" }]');
```

but it ends up throwing a different error:

``` sh
Error: unsupported BodyInit type_initBody@file:///Users/jmeas/...
```

**Comment by johann-sonntagbauer** [comment]
Hi, I am facing some related issue. Haven't found any real solution for now, but try the following:

this.requests[0].responseType = 'text';

Then no convertion should take place and at least your test case should work.

**Comment by johann-sonntagbauer** [comment]
@jmeas one additional note, i used the fetch api. The API enforces binary response types. That caused my problem because the implementation in sinonjs only supports ascii characters.

**Comment by Gpx** [comment]
Hey any update on this? I'm facing the same issue. For the moment I'm using @johann-sonntagbauer suggestion and setting `responseType = 'text'`.

**Comment by islemaster** [comment]
It looks like support for `"blob"` responseTypes [was merged in August 2015](https://github.com/sinonjs/sinon/pull/813) - is it not working?

**Comment by fatso83** [comment]
My guess is this is probably browser dependent and that `Blob` does not pass the `typeof` check. The clue is that it gets past the line 
[`else if (supportsBlob && responseType === "blob"`](https://github.com/sinonjs/sinon/blob/f8091656c6da4411cf25aeaeef6327405bd10356/lib/sinon/util/fake_xml_http_request.js#L323).

Since we know that `responseType` is `"blob"` from the error message, I am guessing something is wrong with the other check: `var supportsBlob = typeof Blob === "function";`.

@islemaster: No details have been given about browsers affected, so could you provide some details? Even better, provide the output of `typeof Blob === "function"`.

[Only newer browsers support Blob](http://caniuse.com/#feat=blobbuilder)

**Comment by islemaster** [comment]
@fatso83 you are exactly correct - my problem is while using PhantomJS, which doesn't support Blob.  I haven't had any luck polyfilling either.
