### ISSUE TITLE
Browserify is called in prepublish script before being available

### ISSUE THREAD

**Issue by fatso83** [sinonjs/sinon#893]
As discovered in #859, browserify is being called in the `prepublish` script.

```
npm install
> ...
>  sinon@1.17.0 prepublish /Users/carl-erik.kopseng/dev-priv/Sinon.JS
> ./build

./build:53:in ``': No such file or directory - ./node_modules/.bin/browserify (Errno::ENOENT)
    from ./build:53:in `block in <main>'
    from ./build:46:in `chdir'
    from ./build:46:in `<main>'
```

The NPM docs says this on the `prepublish` script

> prepublish: Run BEFORE the package is published. (Also run on local npm install without any arguments.)

**Comment by fatso83** [comment]
According to the author of NPM, this is [per-design, and should be handled by a third-party solution](https://github.com/npm/npm/issues/3059#issuecomment-12282746). 

>  I suggest adding a Makefile with a publish: target that does all this stuff, and then runs npm publish at the end of it. Then you'd run make publish instead of npm publish.

@grassator: do you a preference on how to resolve the [issue](https://github.com/sinonjs/sinon/commit/db24a7a7cb643d076537458a4147adc29641420f#diff-b0da275520918e23dd615e2a747528f1R50)? 

I would suggest a pragmatic solution is just adding a `pre-publish` section a la 
`"preinstall" : "npm install browserify"`

**Comment by grassator** [comment]
@fatso83 I don't think that `"preinstall" : "npm install browserify"`, is a good solution because theres no guarantee that `browserify` is the only dependency that is required to run `prepublish` and then syncing these dependencies will become a pain.

My approach would be as suggested by the NPM author and use Make or some other kind of build system, but we need to decide which build system it is.

**Comment by mantoni** [comment]
You can always use npm as a build system.
Here's a good read: http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

There is no such recommendation to use an external tool from the npm team. I personally don't see the need to introduce anything new.

**Comment by grassator** [comment]
@mantoni NPM is totally fine as build tool for simple projects, so should be ok for sinon, however as mentioned in the article, dealing with file operations requires additional dependencies. If it's general consensus, that NPM is the best solution for sinon, then I could work on removing `./build` script in favour of NPM.

**Comment by fatso83** [comment]
@grassator : I am all for a NPM-only build, and help would be most welcome. I don't think that much remains.

#896 might touch somewhat on this.

**Comment by mantoni** [comment]
@grassator @fatso83 Yes, I agree that the `preinstall` script isn't the best solution. I just wanted to state that we don't need another build tool to solve the issue. Sorry for the unclear comment there.

**Comment by grassator** [comment]
Ok, so I will start working on that. I will remove `prepublush` script and instead add a custom NPM task `release`. If there is a way to check if the `prepublush` is called during `npm install` then I will add a hook that notifies that `npm run release` should be used instead of `npm publish`, otherwise I will just add relevant section to the `RELEASE.md`.

**Comment by grassator** [comment]
Ok, so I was able to convert current ruby build script to NPM but I really don't like the result. I think we will have to use something more sophisticated than just NPM scripts, otherwise it will be pretty unmanageable:

https://github.com/grassator/Sinon.JS/commit/fabc40f22ad21e951530721c032592b5021e9aa9

**Comment by cjohansen** [comment]
That looks pretty good to me. Way better than the old `build.sh`

**Comment by mantoni** [comment]
This is obsolete. Closing.
