### ISSUE TITLE
Run tests in real browsers

### ISSUE THREAD

**Issue by mroderick** [sinonjs/sinon#912]
It would be very good if we could run tests in multiple, real browsers in the same build on Travis, that runs tests in node and PhantomJS / SlimerJS

Some browsers to consider (the usual suspects):

* IE9+
* Firefox
* Safari
* Chrome

I imagine that we could use

* SauceLabs
* Browserstack

or similar service that has free options for open source projects.

**Comment by fatso83** [comment]
I have used the karma-browserstack plugin, and I guess we could build something for Buster on top of that, but my [experience with Browserstack](https://oligofren.wordpress.com/2014/05/27/running-karma-tests-on-browserstack) (which I would assume goes for SauceLabs as well) is that you will get a lot of false negatives due to networking issues and have to work a bit to try and minimize the noise. 

So running the tests on multiple browsers should be done, but a failing test is perhaps something to take note of rather than what makes a PR fail or not.

**Comment by mantoni** [comment]
@fatso83 I would try to reach that point, where unit test in real browsers are not failing due to timing issues. I'm using a very large suite of unit tests that run against Selenium on multiple browsers at work. We have almost zero networking / timing issues because we don't do any kind of navigation or timing dependent tests. In case of Sinon, the nature of the individual test cases is also timing and network independent. This is why I'm optimistic that reliable browser tests are totally achievable for Sinon. I have no experience with BrowserStack, but I'm happy with SauceLabs which I'm using for some other OS projects.

**Comment by fatso83** [comment]
@mantoni that seems nice. I think the issues I experience is 90% of the time related to running the tests in the iOS and Android simulators/devices that BrowserStack supplies. IE, FF and Chrome most just works.
