### ISSUE TITLE
Reverted safety check for document.createElement

### ISSUE THREAD

**Issue by klynch67** [sinonjs/sinon#925]
kpdecker's commit (Add safety check for document.createElement)
`https://github.com/sinonjs/sinon/commit/0c3248fa6844ae2181ab2a39a64848526c00e65c#diff-fcd4362a232a46da8739cb9b2de652fc`

which fixes the compile error with message "document.createElement is not a function"

was reverted by the merge (Revert "Merge pull request #653 from eriwen/patch-1)
`https://github.com/sinonjs/sinon/commit/378eea5dcfff9d8ff27ef92af9e11f0252564733#diff-fcd4362a232a46da8739cb9b2de652fc`

That safety check is needed to enable calling `sinon.stub()` when running in NodeJS.

**Comment by fatso83** [comment]
@klynch67 : Hi, you are correct about some good stuff being removed with that revert. My guess is that all of it wasn't intentional. But are you sure about needing the check to call `sinon.stub()`?

We stub in the tests, and the tests run in Node. Just tested as a matter of fact with the master branch. I might add in the lost commit, but could you please show some code that actually breaks in Node?

**Comment by klynch67** [comment]
Hello,
My bad. The day after posting the issue, I discovered that we had a unit test that was leaking a partial "document" definition. I fixed the unit test to clean up the artifact and found that the problem I report no longer reproduced.
Sorry for not updating the issue to show that it isn't an issue any longer.
Sincerely,Kelly

Date: Thu, 3 Dec 2015 07:03:02 -0800
